export const en = {
  // navigation
  'nav.metrics': 'Metric Master',
  'nav.bindings': 'Bindings',
  'nav.dependencies': 'Dependencies',
  'nav.dimensions': 'Dimensions',
  'nav.master-data': 'Master data',
  'nav.backup': 'Import / Export',
  'nav.warnings': 'Warnings',
  'nav.warningsTitle': '{errors} errors · {warnings} warnings · {info} info',
  'nav.more': 'More',
  'nav.language': 'Language',

  // common
  'common.save': 'Save',
  'common.cancel': 'Cancel',
  'common.confirm': 'Confirm',
  'common.create': 'Create',
  'common.delete': 'Delete',
  'common.remove': 'Remove',
  'common.rename': 'Rename',
  'common.edit': 'Edit',
  'common.move': 'Move',
  'common.close': 'Close',
  'common.open': 'Open',
  'common.more': 'More actions',
  'common.noResults': 'No matches',

  // metric fields / enums
  'metric.field.name': 'Name',
  'metric.field.code': 'Code',
  'metric.field.aliases': 'Aliases',
  'metric.field.unit': 'Unit',
  'metric.field.unitId': 'Unit',
  'metric.field.definition': 'Definition',
  'metric.field.owner': 'Owner',
  'metric.field.role': 'Role',
  'metric.field.status': 'Status',
  'metric.field.tags': 'Tags',
  'metric.status.draft': 'Draft',
  'metric.status.approved': 'Approved',
  'metric.status.deprecated': 'Deprecated',
  'metric.role.metric': 'Metric',
  'metric.role.kpi': 'KPI',
  'metric.role.indicator': 'Indicator',
  'metric.role.index': 'Index',

  // bindings
  'binding.type': 'Binding type',
  'binding.type.source': 'Source',
  'binding.type.formula': 'Formula',
  'binding.type.assumption': 'Assumption',
  'binding.type.none': 'None',
  'binding.type.missing': 'Missing',
  'binding.type.source.short': 'Source',
  'binding.type.formula.short': 'Formula',
  'binding.type.assumption.short': 'Assumpt.',
  'binding.type.none.short': '—',
  'binding.type.missing.short': 'Missing',
  'binding.status': 'Binding status',
  'binding.status.draft': 'Draft',
  'binding.status.approved': 'Approved',
  'binding.noneHint': 'No binding for {scenario}. Choose Source, Formula or Assumption to define how this metric gets its value in this scenario.',
  'binding.source.system': 'Source system',
  'binding.source.dataset': 'Dataset / table',
  'binding.source.field': 'Field',
  'binding.source.frequency': 'Frequency',
  'binding.source.owner': 'Data owner',
  'binding.assumption.value': 'Value',
  'binding.assumption.validity': 'Valid from → to',
  'binding.assumption.basis': 'Basis / rationale',
  'binding.assumption.basisPlaceholder': 'Where does this number come from? (plan, benchmark, contract…)',
  'binding.formula': 'Formula',
  'binding.formulaHint': 'Reference metrics in brackets: [CODE], [ALIAS] or [Exact name]. Cross-scenario: [TT:REVENUE].',
  'binding.formulaEmpty': 'Type a formula to see its references.',
  'binding.insertReference': 'Insert a metric reference…',
  'binding.references': 'References ({n})',
  'binding.syntaxError': '{message} (position {pos})',
  'binding.crossScenario': '→ {scenario}',
  'binding.targetUnbound': 'no {scenario} binding',
  'binding.refMissing': 'No metric matches this reference.',
  'binding.refAmbiguous': '{n} metrics match — pick one:',
  'binding.refUnknownScenario': 'Unknown scenario "{code}".',
  'binding.useSuggestion': 'Use this metric',
  'binding.createDraft': 'Create draft metric',
  'binding.createDraftTitle': 'Create draft metric for [{token}]',
  'binding.createDraftConfirm': 'Create draft',
  'binding.draftCreated': 'Draft {code} "{name}" created and linked',
  'binding.legacyCode': 'Legacy code',
  'binding.legacyHint': 'TT-*/GD-* code from the workbook. Metadata only.',
  'binding.note': 'Note',
  'binding.save': 'Save {scenario} binding',
  'binding.saved': '{scenario} binding saved',
  'binding.savedWithMissing': 'Saved. {n} reference(s) could not be resolved — see warnings.',
  'binding.remove': 'Remove binding',
  'binding.removeTitle': 'Remove {scenario} binding?',
  'binding.removeMessage': '"{metric}" will have no {scenario} binding. Formulas referencing it in this scenario will show a warning.',
  'binding.removed': '{scenario} binding removed',
  'frequency.daily': 'Daily',
  'frequency.weekly': 'Weekly',
  'frequency.monthly': 'Monthly',
  'frequency.quarterly': 'Quarterly',
  'frequency.yearly': 'Yearly',

  // coverage
  'coverage.all': 'All',
  'coverage.both': 'Both',
  'coverage.only': '{scenario} only',
  'coverage.none': 'No binding',

  // metric master view
  'mm.structure': 'Structure',
  'mm.addRootNode': 'Add root group',
  'mm.addSubNode': 'Add sub-group',
  'mm.addSubNodeTitle': 'Add sub-group under "{name}"',
  'mm.nodeName': 'Group name',
  'mm.nodeNamePlaceholder': 'e.g. Vận hành dịch vụ',
  'mm.nodeCode': 'Group code (optional)',
  'mm.renameNode': 'Edit group',
  'mm.moveUp': 'Move up',
  'mm.moveDown': 'Move down',
  'mm.moveTo': 'Move to…',
  'mm.moveNodeTitle': 'Move "{name}"',
  'mm.newParent': 'New parent',
  'mm.rootLevel': '(root level)',
  'mm.deleteNodeTitle': 'Delete group "{name}"?',
  'mm.deleteNodeMessage': 'It still contains {metrics} metric placement(s) and {nodes} sub-group(s).',
  'mm.deleteNodeEmpty': 'The group is empty.',
  'mm.deleteMoveToParent': 'Move its contents to the parent group, then delete',
  'mm.nodeDeleted': 'Group "{name}" deleted',
  'mm.metricMoved': 'Moved to "{node}"',
  'mm.allMetrics': 'All metrics',
  'mm.unplaced': 'Not in structure',
  'mm.search': 'Search',
  'mm.searchPlaceholder': 'Search code, name, alias, definition…  ( / )',
  'mm.filter.anyStatus': 'Any status',
  'mm.filter.coverage': 'Binding coverage',
  'mm.filter.anyCoverage': 'Any coverage',
  'mm.filter.advanced': 'More filters',
  'mm.filter.anyRole': 'Any role',
  'mm.filter.anyUnit': 'Any unit',
  'mm.filter.dimension': 'Dimension',
  'mm.filter.anyDimension': 'Any dimension',
  'mm.filter.warningsOnly': 'With warnings only',
  'mm.filter.reset': 'Reset filters',
  'mm.newMetric': 'New metric',
  'mm.newMetricHere': 'New metric in this group',
  'mm.newMetricTitle': 'New metric',
  'mm.noPlacement': '(no structural placement yet)',
  'mm.metricCreated': 'Metric {code} created',
  'mm.col.code': 'Code',
  'mm.col.name': 'Name',
  'mm.col.unit': 'Unit',
  'mm.col.dims': 'Dim',
  'mm.col.dimsTitle': 'Number of linked dimensions',
  'mm.count': '{n} metrics',
  'mm.countFiltered': '{n} of {total} metrics',
  'mm.empty': 'No metrics match. Adjust the filters or create one.',

  // drawer
  'drawer.metricNotFound': 'Metric not found',
  'drawer.section.definition': 'Definition',
  'drawer.section.structure': 'Structure',
  'drawer.section.dimensions': 'Dimensions',
  'drawer.section.bindings': 'Bindings',
  'drawer.section.advanced': 'Advanced',
  'drawer.namePlaceholder': 'Metric name',
  'drawer.codeHint': 'Identification only — never encodes structure, dimension or scenario.',
  'drawer.aliasHint': 'Comma-separated. Aliases are valid formula references.',
  'drawer.noUnit': '— no unit —',
  'drawer.noPlacement': 'This metric is not placed in the structural hierarchy yet.',
  'drawer.addPlacement': 'Add to a structure group…',
  'drawer.removePlacement': 'Remove from this group',
  'drawer.primary': 'Primary placement',
  'drawer.makePrimary': 'Make primary',
  'drawer.noDimensions': 'No dimensions linked. Add the axes this metric can be sliced by.',
  'drawer.addDimension': 'Add a dimension…',
  'drawer.required': 'Required dimension',
  'drawer.requiredShort': 'req.',
  'drawer.maxLevel': 'Maximum hierarchy level',
  'drawer.maxLevelShort': 'max L',
  'drawer.memberCount': '{n} members',
  'drawer.unsaved': 'Unsaved changes',
  'drawer.versionInfo': 'v{v} · {at}',
  'drawer.saveFirst': 'Save or discard your changes before opening another metric.',
  'drawer.saved': 'Saved',
  'drawer.discardTitle': 'Discard unsaved changes?',
  'drawer.discardMessage': 'Your edits to this metric have not been saved.',
  'drawer.discard': 'Discard',
  'drawer.warningsTitle': '{n} issue(s) on this metric',
  'drawer.warningsMore': '+{n} more in the warning center',
  'drawer.menu.openDependencies': 'Open in Dependencies',
  'drawer.menu.copyCode': 'Copy code',
  'drawer.menu.delete': 'Delete metric',
  'drawer.copied': '{code} copied',
  'drawer.deleteTitle': 'Delete "{name}"?',
  'drawer.deleteMessage': 'Its placements, bindings and dimension links are removed too. This cannot be undone.',
  'drawer.deleteMessageUsed': '{n} formula(s) reference this metric. They will keep their text and show a missing-reference warning.',
  'drawer.deleted': '"{name}" deleted',
  'drawer.meta.id': 'Internal id',
  'drawer.meta.version': 'Version',
  'drawer.meta.created': 'Created',
  'drawer.meta.updated': 'Updated',
  'drawer.meta.legacyCodes': 'Legacy codes',
  'drawer.meta.usedBy': 'Used by',
  'drawer.meta.usedByCount': '{n} formula binding(s)',

  // conflict
  'conflict.title': 'Saved elsewhere',
  'conflict.message': 'You loaded version {mine}; the current version is {theirs}. Your changes were not saved.',
  'conflict.deleted': 'This record was deleted by someone else.',
  'conflict.reload': 'Reload latest',
  'conflict.overwrite': 'Overwrite with mine',
  'conflict.keepEditing': 'Keep editing',

  // bindings view
  'bindings.anyType': '{scenario}: any',
  'bindings.legacy': 'Legacy codes',
  'bindings.empty': 'No metrics match these filters.',
  'bindings.summary.total': 'Metric Master',
  'bindings.summary.scenario': '{scenario} bound',

  // dependencies
  'dep.pickRoot': 'Pick a root metric…',
  'dep.cross': 'Cross',
  'dep.crossTitle': 'Follow references across scenarios',
  'dep.depthDown': 'Levels of dependencies',
  'dep.depthDownOpt': '↓ {n}',
  'dep.depthUp': 'Levels of dependents',
  'dep.depthUpOpt': '↑ {n}',
  'dep.crossEdge': 'cross-scenario',
  'dep.legendHint': 'drag to pan · wheel to zoom · double-click a node to re-root',
  'dep.empty': 'Pick a root metric to explore what it depends on and what uses it.',
  'dep.edgeCount': '{n} edges',
  'dep.missing': 'missing',
  'dep.unresolved': 'unresolved reference',
  'dep.missingHint': 'No metric matches [{token}]. Fix the formula or create a draft metric from it in:',
  'dep.fixIn': 'Edit formula of "{name}"',
  'dep.expandDown': 'Show what this depends on',
  'dep.expandUp': 'Show what uses this',
  'dep.collapse': 'Collapse branch',
  'dep.dependsOn': 'Depends on',
  'dep.usedBy': 'Used by',
  'dep.openMetric': 'Open metric',
  'dep.makeRoot': 'Make root',
  'dep.stats': '{nodes} nodes · {edges} edges shown · {total} edges in catalogue · {cycles} cycles',

  // dimensions
  'dims.title': 'Dimensions',
  'dims.new': 'New dimension',
  'dims.empty': 'No dimensions yet.',
  'dims.counts': '{members} members · used by {metrics} metrics',
  'dims.pick': 'Pick a dimension to manage its members.',
  'dims.members': 'Members ({n}, {depth} levels)',
  'dims.addMember': 'Add member',
  'dims.addChild': 'Add child member',
  'dims.addChildTitle': 'Add child under "{name}"',
  'dims.moveToRoot': 'Move to root level',
  'dims.deleteMemberTitle': 'Delete member "{name}"?',
  'dims.deleteMemberChildren': 'Its {n} child member(s) move up one level.',
  'dims.usedBy': 'Used by {n} metrics',
  'dims.notUsed': 'No metric uses this dimension yet.',
  'dims.deleteTitle': 'Delete dimension "{name}"?',
  'dims.deleteMessage': '{members} member(s) and {metrics} metric link(s) will be removed.',

  // master data
  'master.units': 'Units',
  'master.addUnit': 'Add unit',
  'master.usedBy': 'Used by',
  'master.deleteUnitTitle': 'Delete unit "{code}"?',
  'master.deleteUnitUsed': '{n} metric(s) use this unit and will show a warning.',
  'master.scenarios': 'Scenarios',
  'master.scenariosHint': 'TT = actual, GD = planning. Codes are used in formulas ([TT:REVENUE]).',
  'master.bindings': 'Bindings',

  // import / export
  'io.storage': 'Storage',
  'io.storagePersistent': 'Data is stored in this browser (IndexedDB). Export a backup before clearing browser data.',
  'io.storageMemory': 'IndexedDB is unavailable — data lives in memory only for this tab. Export a backup before closing.',
  'io.export': 'Export backup',
  'io.exportHint': 'Downloads the whole catalogue as one JSON file (metrics, structure, bindings, dimensions).',
  'io.downloadJson': 'Download JSON',
  'io.exported': 'Backup downloaded',
  'io.import': 'Import backup',
  'io.importHint': 'Replaces everything with the contents of a JSON backup. Preview first, then confirm.',
  'io.chooseFile': 'Choose JSON file…',
  'io.importReplace': 'Replace all data',
  'io.importTitle': 'Replace all data?',
  'io.importMessage': 'The current {n} metrics and all related records will be replaced by the file contents.',
  'io.imported': 'Imported {n} metrics',
  'io.demo': 'Demo data',
  'io.demoHint': 'Reset to the curated demo catalogue, or load a large synthetic dataset (3,000 metrics, 120 dimensions) to test performance.',
  'io.resetDemo': 'Reset to demo catalogue',
  'io.resetDemoTitle': 'Reset to demo data?',
  'io.resetDemoMessage': 'All current data will be replaced by the demo catalogue.',
  'io.loadLarge': 'Load large dataset (3,000 metrics)',
  'io.loadLargeTitle': 'Load large synthetic dataset?',
  'io.loadLargeMessage': 'All current data will be replaced by a generated catalogue of 3,000 metrics.',
  'io.clearAll': 'Clear everything',
  'io.clearTitle': 'Clear all data?',
  'io.clearMessage': 'Every metric, binding, structure node and dimension will be deleted.',
  'io.replaced': 'Loaded {n} metrics in {ms} ms',
  'io.excel': 'GSM workbook import',
  'io.phase2': 'Phase 2',
  'io.excelHint': 'The Excel workbook will be imported through a staging workflow so that TT and GD rows describing the same business metric are merged deliberately, never by name alone.',
  'io.excelStep1': 'Bảng 1 → structural hierarchy; Giá trị chiều → dimensions and members.',
  'io.excelStep2': 'Bảng 2.1 / 2.2 → TT / GD binding candidates; DIMxx columns → metric ↔ dimension links.',
  'io.excelStep3': 'Suggested canonical matches by normalised name, unit, definition, structure and dimension set.',
  'io.excelStep4': 'You confirm each pair: merge as one metric, or keep separate. TT-*/GD-* codes stay as legacy binding codes.',
  'io.excelImport': 'Import workbook (coming in Phase 2)',

  // warnings
  'warnings.title': 'Warnings',
  'warnings.searchPlaceholder': 'Search issues…',
  'warnings.anyEntity': 'Any entity',
  'warnings.entity': 'Entity',
  'warnings.message': 'Issue',
  'warnings.rule': 'Rule',
  'warnings.revalidate': 'Re-validate',
  'warnings.empty': 'Nothing to report.',
  'warnings.hint': 'Click an issue to jump to it.',
  'warnings.noTarget': 'No place to jump to for this issue.',
  'severity.error': 'Error',
  'severity.warning': 'Warning',
  'severity.info': 'Info',
  'entity.metric': 'Metric',
  'entity.binding': 'Binding',
  'entity.structure': 'Structure',
  'entity.dimension': 'Dimension',
  'entity.member': 'Member',
  'entity.metricDimension': 'Metric × Dimension',
  'entity.metricStructure': 'Placement',

  // collections
  'collection.units': 'units',
  'collection.scenarios': 'scenarios',
  'collection.metrics': 'metrics',
  'collection.structureNodes': 'structure nodes',
  'collection.metricStructures': 'placements',
  'collection.bindings': 'bindings',
  'collection.dimensions': 'dimensions',
  'collection.dimensionMembers': 'dimension members',
  'collection.metricDimensions': 'metric-dimension links',

  // validation issues
  'issue.METRIC_MISSING_NAME': 'Metric {code} has no name',
  'issue.METRIC_MISSING_CODE': '"{name}" has no code',
  'issue.METRIC_DUPLICATE_CODE': 'Code "{code}" is used by {count} metrics',
  'issue.METRIC_UNIT_MISSING': '"{name}" references a unit that no longer exists',
  'issue.METRIC_APPROVED_UNPLACED': 'Approved metric "{name}" is not placed in the structure',
  'issue.METRIC_UNPLACED': 'Draft "{name}" is not placed in the structure yet',
  'issue.METRIC_APPROVED_UNBOUND': 'Approved metric "{name}" has no TT or GD binding',
  'issue.PLACEMENT_ORPHAN': 'A structural placement points to a missing metric or group',
  'issue.STRUCTURE_CYCLE': 'Group "{name}" is part of a parent cycle',
  'issue.STRUCTURE_ORPHAN': 'Group "{name}" references a missing parent',
  'issue.STRUCTURE_MISSING_NAME': 'A structure group has no name',
  'issue.STRUCTURE_DUPLICATE_CODE': 'Group code "{code}" is duplicated',
  'issue.BINDING_ORPHAN': 'A binding points to a missing metric or scenario',
  'issue.BINDING_DUPLICATE': '"{metric}" has {count} bindings for {scenario}',
  'issue.BINDING_FORMULA_EMPTY': '{scenario} formula binding of "{metric}" has no formula',
  'issue.BINDING_FORMULA_SYNTAX': '{scenario} formula of "{metric}": {detail}',
  'issue.BINDING_REF_UNKNOWN_SCENARIO': '{scenario} formula of "{metric}": {ref} uses an unknown scenario',
  'issue.BINDING_REF_AMBIGUOUS': '{scenario} formula of "{metric}": {ref} matches {count} metrics',
  'issue.BINDING_REF_MISSING': '{scenario} formula of "{metric}": {ref} does not match any metric',
  'issue.BINDING_REF_TARGET_UNBOUND': '{scenario} formula of "{metric}" uses "{target}", which has no {targetScenario} binding',
  'issue.BINDING_CROSS_SCENARIO': '{scenario} formula of "{metric}" references {ref} from {targetScenario} (explicit cross-scenario)',
  'issue.BINDING_SOURCE_MISSING_INFO': '{scenario} source binding of "{metric}" has no source information',
  'issue.BINDING_ASSUMPTION_MISSING_VALUE': '{scenario} assumption of "{metric}" has no value',
  'issue.BINDING_ASSUMPTION_MISSING_BASIS': '{scenario} assumption of "{metric}" has no basis / rationale',
  'issue.DIMENSION_MISSING_NAME': 'Dimension {code} has no name',
  'issue.DIMENSION_DUPLICATE_CODE': 'Dimension code "{code}" is duplicated',
  'issue.MEMBER_ORPHAN': 'Member "{name}" belongs to a missing dimension',
  'issue.MEMBER_INVALID_PARENT': 'Member "{name}" has an invalid parent',
  'issue.MEMBER_CYCLE': 'Member "{name}" is part of a cyclic hierarchy',
  'issue.MEMBER_DUPLICATE_CODE': 'Member code "{code}" is duplicated in its dimension',
  'issue.METRIC_DIMENSION_ORPHAN': 'A metric ↔ dimension link points to a missing record',
  'issue.METRIC_DIMENSION_DUPLICATE': '"{metric}" is linked to "{dimension}" more than once',
  'issue.METRIC_DIMENSION_MAXLEVEL': '"{metric}" × "{dimension}": max level {maxLevel} exceeds the hierarchy depth ({depth})',
  'issue.METRIC_DIMENSION_ALLOWED_MISSING': '"{metric}" × "{dimension}": {count} allowed member(s) no longer exist',
  'issue.DEPENDENCY_CYCLE': 'Circular dependency: {path}',
  'io.restorePoints': 'Restore points',
  'io.restoreHint': 'A snapshot is taken automatically before every import, reset or clear. Restore one to undo.',
  'io.restoreEmpty': 'No restore point yet.',
  'io.restoreUnavailable': 'This browser cannot store restore points. Export a JSON backup before replacing data.',
  'io.restoreUnnamed': 'Snapshot',
  'io.restoreCounts': '{metrics} metrics · {bindings} bindings',
  'io.restore': 'Restore',
  'io.restoreTitle': 'Restore this snapshot?',
  'io.restoreMessage': 'The current data will be replaced. A restore point of it is taken first, so this is reversible too.',
  'io.restored': 'Restored {n} metrics',
  'io.undo': 'Undo',
  'io.rejected': 'This file was refused',
  'io.repaired': 'Repaired while reading the file',
  'io.repairedCount': '{n} record(s) repaired or dropped, see the import preview',
  'io.willDelete': 'This file does not contain everything you have now',
  'io.importMessageDeleting': 'The current {n} metrics and all related records will be replaced. {lost} record(s) in collections absent from the file will be deleted.',
  'conflict.reloadOnly': 'This record can only be reloaded, not overwritten.',
  'error.duplicateRelationship': 'That relationship already exists.',
  'io.restoreFailed': 'no restore point could be written, so this cannot be undone. Export a JSON backup.',
};
