export const en = {
  // navigation
  'nav.metrics': 'Metric Master',
  'nav.overview': 'Overview',
  'nav.bindings': 'Bindings',
  'nav.dependencies': 'Dependencies',
  'nav.dimensions': 'Dimensions',
  'nav.structure': 'Structure',
  'nav.master-data': 'Master data',
  'nav.backup': 'Import / Export',
  'nav.warnings': 'Warnings',
  'nav.quality': 'Quality',
  'nav.warningsTitle': '{errors} errors · {warnings} warnings · {info} info',
  'nav.more': 'More',
  'nav.menu': 'Menu',
  'nav.language': 'Language',
  'group.catalogue': 'Catalogue',
  'group.overview': 'Overview',
  'group.structure': 'Structure',
  'group.logic': 'Logic',
  'group.quality': 'Quality',
  'nav.density': 'Density',
  'nav.whatsNew': "What's new",
  'whatsNew.title': "What's new in Metric Studio",
  'whatsNew.subtitle': 'Build {version}. Recent changes, newest first.',
  'whatsNew.foot': 'Shown once per build. Open again any time from More ▾.',
  'overview.subtitle': 'Where the catalogue stands today, and what needs a hand.',
  'overview.catalogue': 'Catalogue',
  'overview.coverage': 'Scenario coverage',
  'overview.attention': 'Requires attention',
  'overview.recent': 'Recently updated',
  'overview.actions': 'Quick actions',
  'overview.metrics': 'metrics',
  'overview.groups': 'groups',
  'overview.reports': 'reports',
  'overview.dimensions': 'dimensions',
  'overview.scenarios': 'scenarios',
  'overview.bindings': 'bindings',
  'overview.byStatus': 'By status',
  'overview.complete': 'complete',
  'overview.partial': 'partial',
  'overview.missing': 'missing',
  'overview.coverageHint': '{complete} of {total} metrics are bound in every scenario.',
  'overview.errors': '{n} errors',
  'overview.warnings': '{n} warnings',
  'overview.unplaced': '{n} metrics not placed in the structure',
  'overview.missingCoverage': '{n} metrics without any binding',
  'overview.drafts': '{n} metrics still in draft',
  'overview.allClear': 'Nothing needs attention right now.',
  'overview.openQuality': 'Open Quality',
  'overview.topIssues': 'Top issues',
  'overview.noRecent': 'No metrics yet.',
  'overview.updated': 'updated {when}',
  'overview.action.newMetric': 'New metric',
  'overview.action.structure': 'Organise the structure',
  'overview.action.bindings': 'Review bindings',
  'overview.action.dependencies': 'Explore dependencies',
  'overview.action.backup': 'Import / Export',
  'overview.action.revalidate': 'Re-validate',
  'overview.storage': 'Storage',
  'density.comfortable': 'Comfortable',
  'density.compact': 'Compact',
  'insights.title': 'Insights',
  'insights.empty': 'Select a row to see its details here.',
  'insights.collapse': 'Collapse panel',
  'insights.expand': 'Show panel',
  'insights.resize': 'Drag to resize',
  'insights.coverage': 'Scenario coverage',
  'insights.lineage': 'Lineage',
  'insights.usedBy': 'Used by',
  'insights.dependsOn': 'Depends on',
  'insights.noIssues': 'No issues',
  'insights.noDefinition': 'No definition yet.',
  'insights.noDimensions': 'No dimensions linked.',
  'insights.editMetric': 'Edit metric',
  'filters.add': 'Filters',
  'filters.clear': 'Clear filters',
  'filters.any': 'Any {label}',

  // common
  'common.save': 'Save',
  'common.cancel': 'Cancel',
  'common.confirm': 'Confirm',
  'common.create': 'Create',
  'common.delete': 'Delete',
  'common.remove': 'Remove',
  'common.rename': 'Rename',
  'common.edit': 'Edit',
  'common.move': 'Move',
  'common.close': 'Close',
  'common.open': 'Open',
  'common.more': 'More actions',
  'common.noResults': 'No matches',

  // metric fields / enums
  'metric.field.name': 'Name',
  'metric.field.code': 'Code',
  'metric.field.aliases': 'Aliases',
  'metric.field.unit': 'Unit',
  'metric.field.unitId': 'Unit',
  'metric.field.definition': 'Definition',
  'metric.field.owner': 'Owner',
  'metric.field.owners': 'Owners',
  'drawer.ownersPlaceholder': 'Type a name, Enter to add',
  'drawer.ownersHint': 'Several owners are fine: one chip each.',
  'metric.field.role': 'Role',
  'metric.field.status': 'Status',
  'metric.field.tags': 'Tags',
  'metric.status.draft': 'Draft',
  'metric.status.approved': 'Approved',
  'metric.status.deprecated': 'Deprecated',
  'metric.role.metric': 'Metric',
  'metric.role.kpi': 'KPI',
  'metric.role.indicator': 'Indicator',
  'metric.role.index': 'Index',

  // bindings
  'binding.type': 'Binding type',
  'binding.type.source': 'Source',
  'binding.type.formula': 'Formula',
  'binding.type.assumption': 'Assumption',
  'binding.type.none': 'None',
  'binding.type.missing': 'Missing',
  'binding.type.source.short': 'Source',
  'binding.type.formula.short': 'Formula',
  'binding.type.assumption.short': 'Assumpt.',
  'binding.type.none.short': '—',
  'binding.type.missing.short': 'Missing',
  'binding.status': 'Binding status',
  'binding.status.draft': 'Draft',
  'binding.status.approved': 'Approved',
  'binding.noneHint': 'No binding for {scenario}. Choose Source, Formula or Assumption to define how this metric gets its value in this scenario.',
  'binding.source.system': 'Source system',
  'binding.source.dataset': 'Dataset / table',
  'binding.source.field': 'Field',
  'binding.source.frequency': 'Frequency',
  'binding.source.owner': 'Data owner',
  'binding.assumption.value': 'Value',
  'binding.assumption.validity': 'Valid from → to',
  'binding.assumption.basis': 'Basis / rationale',
  'binding.assumption.basisPlaceholder': 'Where does this number come from? (plan, benchmark, contract…)',
  'binding.formula': 'Formula',
  'binding.formulaHint': 'Reference metrics in brackets: [CODE], [ALIAS] or [Exact name]. Cross-scenario: [TT:REVENUE].',
  'binding.formulaPlaceholder': 'Type [ to pick a metric, then operators as text: [VOLUME] * [PRICE]',
  'binding.pickerHint': '↑ ↓ to move · Enter to insert · Esc to close',
  'binding.legendResolved': 'resolved',
  'binding.legendMissing': 'no match',
  'binding.legendAmbiguous': 'several matches',
  'binding.formulaEmpty': 'Type a formula to see its references.',
  'binding.insertReference': 'Insert a metric reference…',
  'binding.pickAmbiguous': '"{name}" ({code}) cannot be referenced unambiguously: its code and aliases clash with other metrics. Give it a unique code first.',
  'binding.references': 'References ({n})',
  'binding.syntaxError': '{message} (position {pos})',
  'binding.crossScenario': '→ {scenario}',
  'binding.targetUnbound': 'no {scenario} binding',
  'binding.refMissing': 'No metric matches this reference.',
  'binding.refAmbiguous': '{n} metrics match — pick one:',
  'binding.refUnknownScenario': 'Unknown scenario "{code}".',
  'binding.useSuggestion': 'Use this metric',
  'binding.createDraft': 'Create draft metric',
  'binding.createDraftTitle': 'Create draft metric for [{token}]',
  'binding.createDraftConfirm': 'Create draft',
  'binding.draftCreated': 'Draft {code} "{name}" created and linked',
  'binding.freeText': 'Free-text formula',
  'binding.freeTextTag': 'text',
  'binding.freeTextHint': 'For the rare formula that cannot be written as an expression. Not checked and not executable; always reported as a warning. Write every input it consists of in brackets — [CODE] — so its dependencies are known.',
  'binding.freeTextNotice': 'Free text — not checked. {n} reference(s) declared in brackets.',
  'binding.freeTextNoRefs': 'Free text with no declared reference. Put each input in brackets, e.g. [CODE], so the dependency graph knows what this consists of.',
  'binding.freeTextInsight': 'Free-text formula: a description in words. Not checked, not executable; its bracketed references are the declared inputs.',
  'binding.markFreeTextHint': 'Not meant to be an expression?',
  'binding.markFreeText': 'Mark as free text',
  'binding.formulaPlaceholderText': 'Describe the calculation in words and put each input in brackets: weighted by the SOP v3 table from [VOLUME] and [PRICE]',
  'binding.mode.expression': 'Expression',
  'binding.mode.text': 'Free text',
  'mm.filter.freeText': 'Free-text formulas only',
  'binding.legacyCode': 'Legacy code',
  'binding.legacyHint': 'TT-*/GD-* code from the workbook. Metadata only.',
  'binding.note': 'Note',
  'binding.save': 'Save {scenario} binding',
  'binding.saved': '{scenario} binding saved',
  'binding.savedWithMissing': 'Saved. {n} reference(s) could not be resolved — see warnings.',
  'binding.remove': 'Remove binding',
  'binding.removeTitle': 'Remove {scenario} binding?',
  'binding.removeMessage': '"{metric}" will have no {scenario} binding. Formulas referencing it in this scenario will show a warning.',
  'binding.removed': '{scenario} binding removed',
  'frequency.daily': 'Daily',
  'frequency.weekly': 'Weekly',
  'frequency.monthly': 'Monthly',
  'frequency.quarterly': 'Quarterly',
  'frequency.yearly': 'Yearly',

  // coverage
  'coverage.all': 'All',
  'coverage.both': 'Both',
  'coverage.only': '{scenario} only',
  'coverage.none': 'No binding',
  'coverage.complete': 'Complete',
  'coverage.partial': 'Partial',
  'coverage.missing': 'Missing',

  // metric master view
  'mm.structure': 'Structure',
  'mm.contextHint': 'Click a row to inspect · double-click or Enter to edit',
  'mm.rowHint': 'Click to inspect · double-click to edit · drag onto a group to place',
  'mm.openStructure': 'Open the Structure workspace',
  'mm.openInStructure': 'Open in Structure',
  'mm.showMetrics': 'Show metrics',
  'mm.addRootNode': 'Add root group',
  'mm.addSubNode': 'Add sub-group',
  'mm.addSubNodeTitle': 'Add sub-group under "{name}"',
  'mm.nodeName': 'Group name',
  'mm.nodeNamePlaceholder': 'e.g. Vận hành dịch vụ',
  'mm.nodeCode': 'Group code (optional)',
  'mm.renameNode': 'Edit group',
  'mm.moveUp': 'Move up',
  'mm.moveDown': 'Move down',
  'mm.moveTo': 'Move to…',
  'mm.moveNodeTitle': 'Move "{name}"',
  'mm.newParent': 'New parent',
  'mm.rootLevel': '(root level)',
  'mm.deleteNodeTitle': 'Delete group "{name}"?',
  'mm.deleteNodeMessage': 'It still contains {metrics} metric placement(s) and {nodes} sub-group(s).',
  'mm.deleteNodeEmpty': 'The group is empty.',
  'mm.deleteMoveToParent': 'Move its contents to the parent group, then delete',
  'mm.nodeDeleted': 'Group "{name}" deleted',
  'mm.metricMoved': 'Moved to "{node}"',
  'mm.allMetrics': 'All metrics',
  'mm.unplaced': 'Not in structure',
  'mm.search': 'Search',
  'mm.searchPlaceholder': 'Search code, name, alias, definition…  ( / )',
  'mm.filter.anyStatus': 'Any status',
  'mm.filter.coverage': 'Binding coverage',
  'mm.filter.anyCoverage': 'Any coverage',
  'mm.filter.advanced': 'More filters',
  'mm.filter.anyRole': 'Any role',
  'mm.filter.anyUnit': 'Any unit',
  'mm.filter.dimension': 'Dimension',
  'mm.filter.anyDimension': 'Any dimension',
  'mm.filter.warningsOnly': 'With warnings only',
  'mm.filter.direct': 'This group only',
  'mm.filtersClearedToReveal': 'Filters were cleared to show the metric you asked for.',
  'mm.nodeGone': 'That group no longer exists — showing all metrics.',
  'mm.filter.reset': 'Reset filters',
  'mm.newMetric': 'New metric',
  'mm.newMetricHere': 'New metric in this group',
  'mm.newMetricTitle': 'New metric',
  'mm.noPlacement': '(no structural placement yet)',
  'mm.metricCreated': 'Metric {code} created',
  'mm.col.code': 'Code',
  'mm.col.name': 'Name',
  'mm.col.unit': 'Unit',
  'mm.col.dims': 'Dim',
  'mm.col.dimsTitle': 'Number of linked dimensions',
  'mm.count': '{n} metrics',
  'mm.countFiltered': '{n} of {total} metrics',
  'mm.empty': 'No metrics match. Adjust the filters or create one.',
  'mm.noData': 'No metrics yet. Create the first one, or import a backup.',
  'mm.noResults': 'No metrics match the search and filters.',
  'mm.emptyScope': 'No metrics in this group yet.',

  // drawer
  'drawer.metricNotFound': 'Metric not found',
  'drawer.section.definition': 'Definition',
  'drawer.section.structure': 'Structure',
  'drawer.section.dimensions': 'Dimensions',
  'drawer.section.bindings': 'Bindings',
  'drawer.section.advanced': 'Advanced',
  'drawer.namePlaceholder': 'Metric name',
  'drawer.codeHint': 'Identification only — never encodes structure, dimension or scenario.',
  'drawer.aliasHint': 'Comma-separated. Aliases are valid formula references.',
  'drawer.noUnit': '— no unit —',
  'drawer.noPlacement': 'This metric is not placed in the structural hierarchy yet.',
  'drawer.addPlacement': 'Add to a structure group…',
  'drawer.removePlacement': 'Remove from this group',
  'drawer.primary': 'Primary placement',
  'drawer.makePrimary': 'Make primary',
  'drawer.groups': 'Groups',
  'drawer.reports': 'Reports',
  'drawer.noReports': 'This metric is not shown in any report yet.',
  'drawer.addReport': 'Add to a report…',
  'drawer.removeReport': 'Remove from this report',
  'insights.noReports': 'Not in any report',
  'drawer.noDimensions': 'No dimensions linked. Add the axes this metric can be sliced by.',
  'drawer.addDimension': 'Add a dimension…',
  'drawer.required': 'Required dimension',
  'drawer.requiredShort': 'req.',
  'drawer.maxLevel': 'Maximum hierarchy level',
  'drawer.maxLevelShort': 'max L',
  'drawer.memberCount': '{n} members',
  'drawer.unsaved': 'Unsaved changes',
  'drawer.versionInfo': 'v{v} · {at}',
  'drawer.saveFirst': 'Save or discard your changes before opening another metric.',
  'drawer.saveFirstWhat': 'Unsaved: {what}. Save or discard before opening another metric.',
  'drawer.saveAllAndGo': 'Save all and open',
  'drawer.discardAndGo': 'Discard and open',
  'drawer.saveAllCount': 'Save all ({n})',
  'drawer.saveCovers': 'Saves everything pending: {what}',
  'drawer.pending.metric': 'the metric fields',
  'drawer.pending.binding': 'the {scenarios} binding',
  'drawer.pending.bindings': 'the {scenarios} bindings',
  'drawer.pending.join': ' and ',
  'drawer.saved': 'Saved',
  'drawer.discardTitle': 'Discard unsaved changes?',
  'drawer.discardMessage': 'Your edits to this metric have not been saved.',
  'drawer.discard': 'Discard',
  'drawer.unsavedTitle': 'Unsaved changes',
  'drawer.unsavedMessage': 'Unsaved: {what}.',
  'drawer.saveAndClose': 'Save all and close',
  'drawer.stay': 'Keep editing',
  'drawer.warningsTitle': '{n} issue(s) on this metric',
  'drawer.warningsMore': '+{n} more in the warning center',
  'drawer.menu.openDependencies': 'Open in Dependencies',
  'drawer.menu.copyCode': 'Copy code',
  'drawer.menu.delete': 'Delete metric',
  'drawer.copied': '{code} copied',
  'drawer.deleteTitle': 'Delete "{name}"?',
  'drawer.deleteMessage': 'Its placements, bindings and dimension links are removed too. This cannot be undone.',
  'drawer.deleteMessageUsed': '{n} formula(s) reference this metric. They will keep their text and show a missing-reference warning.',
  'drawer.deleted': '"{name}" deleted',
  'drawer.meta.id': 'Internal id',
  'drawer.meta.version': 'Version',
  'drawer.meta.created': 'Created',
  'drawer.meta.updated': 'Updated',
  'drawer.meta.legacyCodes': 'Legacy codes',
  'drawer.meta.usedBy': 'Used by',
  'drawer.meta.usedByCount': '{n} formula binding(s)',

  // conflict
  'conflict.title': 'Saved elsewhere',
  'conflict.message': 'You loaded version {mine}; the current version is {theirs}. Your changes were not saved.',
  'conflict.deleted': 'This record was deleted by someone else.',
  'conflict.staleEditor': 'A save for a metric you have since left was refused because it changed elsewhere. Open it again to see the current version.',
  'conflict.reload': 'Reload latest',
  'conflict.overwrite': 'Overwrite with mine',
  'conflict.keepEditing': 'Keep editing',

  // bindings view
  'bindings.anyType': '{scenario}: any',
  'bindings.legacy': 'Legacy codes',
  'bindings.empty': 'No metrics match these filters.',
  'bindings.summary.total': 'Metric Master',
  'bindings.summary.scenario': '{scenario} bound',
  'bindings.subtitle': 'One row per metric, one cell per scenario.',
  'bindings.scenarioContext': 'Scenarios',
  'bindings.allScenarios': 'All scenarios',
  'bindings.contextHint': 'Click a cell to inspect · double-click or Enter to edit · ← → move between scenarios',
  'bindings.partialReset': '"Partial" does not apply with one scenario in context — showing all.',
  'bindings.pick': 'Select a row to inspect the metric, or a cell to inspect one binding.',
  'bindings.typeFilter': '{scenario} binding',
  'bindings.editBinding': 'Edit binding',
  'bindings.addBinding': 'Add binding',
  'bindings.noBinding': 'No binding in {scenario} yet.',
  'bindings.references': 'References',
  'bindings.noReferences': 'No references.',
  'bindings.updated': 'Updated',
  'bindings.legacyShort': 'Legacy',
  'bindings.coverageOf': '{bound} of {total} scenarios bound',
  'bindings.inScenario': 'in {scenario}',
  'bindings.openInMaster': 'Open in Metric Master',
  'bindings.formulaErrors': 'Formula errors',

  // dependencies
  'dep.pickRoot': 'Pick a root metric…',
  'dep.subtitle': 'What a metric depends on and what uses it, one scenario at a time.',
  'dep.root': 'Root',
  'dep.scenario': 'Scenario',
  'dep.noRoot': 'No root yet',
  'dep.contextHint': 'Click a node to inspect · double-click to re-root · + / − to expand or collapse',
  'dep.pickNode': 'Select a node to inspect its binding and neighbours.',
  'dep.inGraph': 'In this graph',
  'dep.tableHint': 'Click an edge to inspect its target · double-click or Enter to edit',
  'dep.scopeLabel': 'Scope',
  'dep.scope.graph': 'This graph',
  'dep.scope.all': 'All catalogue',
  'dep.tableCountGraph': '{n} edges in this graph',
  'dep.tableNoRoot': 'Pick a root metric to list the edges of its graph, or switch the scope to the whole catalogue.',
  'dep.cross': 'Cross',
  'dep.crossTitle': 'Follow references across scenarios',
  'dep.depthDown': 'Levels of dependencies',
  'dep.depthDownOpt': '↓ {n}',
  'dep.depthUp': 'Levels of dependents',
  'dep.depthUpOpt': '↑ {n}',
  'dep.crossEdge': 'cross-scenario',
  'dep.legendHint': 'drag to pan · wheel to zoom · double-click a node to re-root',
  'dep.empty': 'Pick a root metric to explore what it depends on and what uses it.',
  'dep.edgeCount': '{n} edges',
  'dep.missing': 'missing',
  'dep.unresolved': 'unresolved reference',
  'dep.missingHint': 'No metric matches [{token}]. Fix the formula or create a draft metric from it in:',
  'dep.fixIn': 'Edit formula of "{name}"',
  'dep.expandDown': 'Show what this depends on',
  'dep.expandUp': 'Show what uses this',
  'dep.collapse': 'Collapse branch',
  'dep.dependsOn': 'Depends on',
  'dep.usedBy': 'Used by',
  'dep.openMetric': 'Open metric',
  'dep.makeRoot': 'Make root',
  'dep.stats': '{nodes} nodes · {edges} edges shown · {total} edges in catalogue · {cycles} cycles',
  'dep.viewMode': 'View',
  'dep.mode.graph': 'Graph',
  'dep.mode.table': 'Table',
  'dep.tableSearch': 'Search target, source or formula…',
  'dep.tableEmpty': 'No dependencies match.',
  'dep.tableCount': '{n} of {total} edges',
  'dep.anyScenario': 'Any scenario',
  'dep.sameEdge': 'same scenario',
  'dep.col.targetScenario': 'Scenario',
  'dep.col.target': 'Target metric',
  'dep.col.type': 'Binding',
  'dep.col.sourceScenario': 'Src scen.',
  'dep.col.source': 'Source metric',
  'dep.col.seq': 'Seq',
  'dep.col.refType': 'Reference',
  'dep.col.dimension': 'Dimension context',
  'dep.col.operator': 'Operator',
  'dep.unknownScenario': 'unknown scenario',
  'dep.unknownScenarioHint': 'No scenario has the code {code}, so this reference points nowhere. Fix the scenario prefix in the formula, or add the scenario under More ▾ → Master data.',
  'dep.truncated': 'Too large to draw in full — showing at most {n} nodes and {e} connections. Reduce the depth or pick a closer root to see the rest.',

  // dimensions
  'dims.title': 'Dimensions',
  'dims.membersPane': 'Members',
  'dims.new': 'New dimension',
  'dims.empty': 'No dimensions yet.',
  'dims.counts': '{members} members · used by {metrics} metrics',
  'dims.pick': 'Pick a dimension to manage its members.',
  'dims.members': 'Members ({n}, {depth} levels)',
  'dims.addMember': 'Add member',
  'dims.addChild': 'Add child member',
  'dims.addChildTitle': 'Add child under "{name}"',
  'dims.moveToRoot': 'Move to root level',
  'dims.deleteMemberTitle': 'Delete member "{name}"?',
  'dims.deleteMemberChildren': 'Its {n} child member(s) move up one level.',
  'dims.usedBy': 'Used by {n} metrics',
  'dims.notUsed': 'No metric uses this dimension yet.',
  'dims.deleteTitle': 'Delete dimension "{name}"?',
  'dims.deleteMessage': '{members} member(s) and {metrics} metric link(s) will be removed.',
  'dims.subtitle': 'Master data every metric can be sliced by: members, levels and aliases.',
  'dims.meta': '{dimensions} dimensions · {members} members',
  'dims.noMembers': 'No members yet. Add one to start the hierarchy.',
  'dims.pickMember': 'Select a member for its details, or keep the dimension selected for an overview.',
  'dims.member': 'Member',
  'dims.dimension': 'Dimension',
  'dims.level': 'Level',
  'dims.parent': 'Parent',
  'dims.rootMember': 'Root member',
  'dims.membersStat': 'members',
  'dims.depthStat': 'levels',
  'dims.childrenStat': 'direct children',
  'dims.subtreeStat': 'in subtree',
  'dims.metricsStat': 'metrics use it',
  'dims.moveTo': 'Move to…',
  'dims.moveMemberTitle': 'Move "{name}" under',
  'dims.newParent': 'New parent',
  'dims.memberMoved': 'Moved "{name}" under "{parent}"',
  'dims.usedByList': 'Used by',
  'dims.andMore': '… and {n} more',
  'dims.dimensionGone': 'That dimension no longer exists.',

  'structure.subtitle': 'The hierarchy on the left says where each metric belongs; the reports on the right say where it is shown.',
  'structure.hierarchy': 'Hierarchy',
  'structure.empty': 'No groups yet. Add a root group to start organising metrics.',
  'structure.pick': 'Select a group or a report to see what it holds and where it sits.',
  'structure.path': 'Path',
  'structure.contents': 'Contents',
  'structure.directMetrics': 'metrics here',
  'structure.totalMetrics': 'metrics in subtree',
  'structure.subGroups': 'sub-groups',
  'structure.directList': 'Metrics in this group ({n})',
  'structure.andMore': '… and {n} more',
  'structure.meta': '{nodes} groups · {roots} roots · {unplaced} unplaced metrics',
  'hierarchy.expandAll': 'Expand all',
  'hierarchy.collapseAll': 'Collapse all',
  'reports.title': 'Reports',
  'reports.empty': 'No reports yet. Create a folder or a report, then link metrics to it.',
  'reports.addFolder': 'Add folder',
  'reports.addReport': 'Add report',
  'reports.addFolderIn': 'Add folder in "{name}"',
  'reports.addReportIn': 'Add report in "{name}"',
  'reports.folderName': 'Folder name',
  'reports.reportName': 'Report name',
  'reports.folderPlaceholder': 'e.g. Board reports',
  'reports.reportPlaceholder': 'e.g. Monthly BOD pack',
  'reports.code': 'Report code (optional)',
  'reports.kind': 'Kind',
  'reports.kind.folder': 'Folder',
  'reports.kind.report': 'Report',
  'reports.editFolder': 'Edit folder',
  'reports.editReport': 'Edit report',
  'reports.newParent': 'New folder',
  'reports.deleteTitle': 'Delete "{name}"?',
  'reports.deleteFolderMessage': 'It still holds {n} sub-item(s).',
  'reports.deleteReportMessage': 'It still shows {n} metric(s).',
  'reports.deleteEmpty': 'It is empty.',
  'reports.deleteMoveUp': 'Move its contents up one level, then delete',
  'reports.deleteUnlink': 'Remove the metric links, then delete',
  'reports.deleted': '"{name}" deleted',
  'reports.gone': 'That report no longer exists.',
  'reports.metricLinked': 'Linked to "{report}"',
  'reports.metricMoved': 'Moved to "{report}"',
  'reports.linkMetric': 'Link a metric…',
  'reports.unlink': 'Remove from this report',
  'reports.linkedList': 'Metrics in this report ({n})',
  'reports.noMetrics': 'No metric linked yet. Pick one below, or drag one across from a group.',
  'reports.insideList': 'Reports in this folder ({n})',
  'reports.noReportsInside': 'No report inside yet.',
  'reports.metricsStat': 'metrics',
  'reports.reportsStat': 'reports',
  'reports.foldersStat': 'sub-folders',
  'reports.countReport': '{n} metrics',
  'reports.countFolder': '{metrics} metrics in {reports} reports',
  'reports.meta': '{reports} reports · {folders} folders',
  'reports.dragHint': 'Drag a metric onto a report to show it there',

  // master data
  'master.units': 'Units',
  'master.addUnit': 'Add unit',
  'master.usedBy': 'Used by',
  'master.deleteUnitTitle': 'Delete unit "{code}"?',
  'master.deleteUnitUsed': '{n} metric(s) use this unit and will show a warning.',
  'master.scenarios': 'Scenarios',
  'master.scenariosHint': 'The contexts a metric can be bound in — for example Actual and Planning. Define as many as you need; the code is what formulas use to reach across ([CODE:METRIC]).',
  'master.addScenario': 'Add scenario',
  'master.scenarioCode': 'Code (short, used in formulas)',
  'master.scenarioName': 'Name',
  'master.scenarioDescription': 'Description',
  'master.scenarioCodeTaken': 'Scenario code "{code}" is already used.',
  'master.scenarioCodeInvalid': 'A scenario code starts with a letter, then up to 7 letters, digits or underscores.',
  'master.deleteScenarioTitle': 'Delete scenario "{code}"?',
  'master.deleteScenarioUsed': '{n} binding(s) belong to this scenario. Remove them first; a scenario in use cannot be deleted.',
  'master.deleteScenarioMessage': 'Metrics keep their other bindings. Formulas that reference [{code}:…] will report an unknown scenario.',
  'master.bindings': 'Bindings',

  // import / export
  'io.storage': 'Storage',
  'io.storagePersistent': 'Data is stored in this browser (IndexedDB). Export a backup before clearing browser data.',
  'io.storageMemory': 'IndexedDB is unavailable — data lives in memory only for this tab. Export a backup before closing.',
  'io.storageUnsaved': 'Your saved catalogue could not be opened. Nothing you do in this session is saved — export a backup before closing.',
  'io.storageSuperseded': 'Another tab opened a newer version of Metric Studio and took over the database. Reload this tab to continue.',
  'io.reload': 'Reload',
  'io.storageReadOnly': 'Saving is off: another tab took over the database. Reload to continue.',
  'io.storageBanner.unsynced': 'A change was only partly saved and the current state could not be re-read. Reload before continuing.',
  'io.csvSafeHint': 'CSV files are prepared for Excel: a cell starting with =, +, − or @ gets a leading apostrophe so it opens as text, not as a formula.',
  'io.migrationDeduplicated': 'Storage upgraded: {n} duplicate relationship(s) from an earlier version were removed.',
  'io.recovery.title': 'Your data could not be opened',
  'io.recovery.blocked': 'Another browser tab is still running an older version of Metric Studio and is holding the database. Close the other tab, then retry.',
  'io.recovery.upgradeFailed': 'The storage upgrade did not complete. Retry once; if it fails again, continue without saving and export a backup from Import / Export.',
  'io.recovery.openFailed': 'The browser refused to open the database. Retry; if it keeps failing, continue without saving and export a backup.',
  'io.recovery.superseded': 'A newer version of Metric Studio took over the database from another tab. Reload to use that version.',
  'io.recovery.dataSafe': 'Nothing has been deleted. Your catalogue is still stored in this browser.',
  'io.recovery.retry': 'Retry',
  'io.recovery.continue': 'Continue without saving',
  'io.export': 'Export backup',
  'io.exportHint': 'Downloads the whole catalogue as one JSON file (metrics, structure, bindings, dimensions).',
  'io.downloadJson': 'Download JSON',
  'io.exported': 'Backup downloaded',
  'io.downloadBindingsCsv': 'Bindings table (CSV)',
  'io.bindingsCsvHint': 'One row per metric × scenario, with the formula text.',
  'io.downloadEdgesCsv': 'Dependency edges (CSV)',
  'io.edgesCsvHint': 'One row per reference inside a formula: target, source, scenario, sequence, operator.',
  'io.import': 'Import backup',
  'io.importHint': 'Replaces everything with the contents of a JSON backup. Preview first, then confirm.',
  'io.chooseFile': 'Choose JSON file…',
  'io.importReplace': 'Replace all data',
  'io.importTitle': 'Replace all data?',
  'io.importMessage': 'The current {n} metrics and all related records will be replaced by the file contents.',
  'io.imported': 'Imported {n} metrics',
  'io.demo': 'Demo data',
  'io.demoHint': 'Reset to the curated demo catalogue, or load a large synthetic dataset (3,000 metrics, 120 dimensions) to test performance.',
  'io.resetDemo': 'Reset to demo catalogue',
  'io.resetDemoTitle': 'Reset to demo data?',
  'io.resetDemoMessage': 'All current data will be replaced by the demo catalogue.',
  'io.loadLarge': 'Load large dataset (3,000 metrics)',
  'io.loadLargeTitle': 'Load large synthetic dataset?',
  'io.loadLargeMessage': 'All current data will be replaced by a generated catalogue of 3,000 metrics.',
  'io.clearAll': 'Clear everything',
  'io.clearTitle': 'Clear all data?',
  'io.clearMessage': 'Every metric, binding, structure node and dimension will be deleted.',
  'io.replaced': 'Loaded {n} metrics in {ms} ms',
  'io.excelExport': 'Export to Excel',
  'io.excelExportHint': 'A formatted workbook in the app\'s theme: choose the datasets and the fields you want, and get one sheet per dataset with a cover sheet in front.',
  'io.excelExportChoose': 'Choose datasets and fields…',
  'io.excelExportAll': 'Download everything (.xlsx)',
  'io.excelExported': 'Workbook downloaded ({sheets} sheets)',
  'io.excelImport': 'Import from Excel',
  'io.excelImportHint': 'Fill the template — one sheet per kind of record, with examples — and import it here. Codes are the keys: a row that matches an existing code updates it, the rest are created, and blank cells keep what is there. Preview first; a restore point is taken before anything changes.',
  'io.excelSheets': 'Sheets: {sheets}',
  'io.templateBlank': 'Download blank template',
  'io.templateFilled': 'Download template with my data',
  'io.chooseExcel': 'Choose Excel file…',
  'io.excelTemplateDownloaded': 'Template downloaded',
  'io.excelReading': 'Reading workbook…',
  'io.excelRowsBySheet': 'Rows read',
  'io.excelPlan': 'What this import will do',
  'io.excelCreate': '{n} new',
  'io.excelUpdate': '{n} updated',
  'io.excelRemove': '{n} removed',
  'io.excelNoChange': 'This file changes nothing: every row matches what the catalogue already has.',
  'io.excelErrors': 'Fix these rows, then choose the file again',
  'io.excelErrorRow': '{sheet} · row {row}: {message}',
  'io.excelWarnings': 'Ignored',
  'io.excelApply': 'Import into catalogue',
  'io.excelTitle': 'Import this workbook?',
  'io.excelMessage': '{create} record(s) will be created, {update} updated in place and {remove} link(s) removed. A restore point is taken first, so this can be undone.',
  'io.excelImported': 'Imported from Excel: {create} created, {update} updated',
  'io.excelStale': 'The catalogue changed while this file was open, so nothing was imported. Read the file again to see what it would do now.',
  'xl.dialogTitle': 'Export to Excel',
  'xl.dialogHint': 'Tick the datasets to include; open Fields to keep only the columns you need. One sheet per dataset, in this order.',
  'xl.fields': 'Fields',
  'xl.fieldsCount': '{n} of {total} fields',
  'xl.selectAll': 'All',
  'xl.selectNone': 'None',
  'xl.cover': 'Include a cover sheet',
  'xl.download': 'Download workbook',
  'xl.rows': '{n} rows',
  'xl.nothing': 'Choose at least one dataset with at least one field.',

  // warnings
  'warnings.title': 'Warnings',
  'warnings.searchPlaceholder': 'Search issues…',
  'warnings.anyEntity': 'Any entity',
  'warnings.entity': 'Entity',
  'warnings.message': 'Issue',
  'warnings.rule': 'Rule',
  'warnings.revalidate': 'Re-validate',
  'warnings.empty': 'Nothing to report.',
  'warnings.hint': 'Click an issue to jump to it.',
  'warnings.noTarget': 'No place to jump to for this issue.',
  'quality.subtitle': 'Every rule the catalogue breaks, and where to go to fix it.',
  'quality.kpi.metricsAffected': 'metrics affected',
  'quality.kpi.clean': 'metrics clean',
  'quality.pick': 'Select an issue to see what it is about and where to fix it.',
  'quality.hint': 'Click an issue to inspect · double-click or Enter to jump to it',
  'quality.filter.severity': 'Severity',
  'quality.filter.entity': 'Entity',
  'quality.filter.rule': 'Rule',
  'quality.filter.scenario': 'Scenario',
  'quality.issues': '{n} issues',
  'quality.issuesFiltered': '{n} of {total} issues',
  'quality.about': 'About',
  'quality.metric': 'Metric',
  'quality.scenario': 'Scenario',
  'quality.node': 'Group',
  'quality.report': 'Report',
  'quality.dimension': 'Dimension',
  'quality.member': 'Member',
  'quality.fix': 'Go to the problem',
  'quality.openInMaster': 'Open in Metric Master',
  'quality.openInBindings': 'Open in Bindings',
  'quality.issueGone': 'That issue is no longer reported.',
  'quality.noResults': 'No issues match these filters ({total} reported in total).',
  'severity.error': 'Error',
  'severity.warning': 'Warning',
  'severity.info': 'Info',
  'entity.metric': 'Metric',
  'entity.binding': 'Binding',
  'entity.structure': 'Structure',
  'entity.dimension': 'Dimension',
  'entity.member': 'Member',
  'entity.metricDimension': 'Metric × Dimension',
  'entity.metricStructure': 'Placement',
  'entity.report': 'Report',
  'entity.metricReport': 'Metric × Report',

  // collections
  'collection.units': 'units',
  'collection.scenarios': 'scenarios',
  'collection.metrics': 'metrics',
  'collection.structureNodes': 'structure nodes',
  'collection.metricStructures': 'placements',
  'collection.bindings': 'bindings',
  'collection.dimensions': 'dimensions',
  'collection.dimensionMembers': 'dimension members',
  'collection.metricDimensions': 'metric-dimension links',
  'collection.reports': 'reports',
  'collection.metricReports': 'metric-report links',

  // validation issues
  'issue.METRIC_MISSING_NAME': 'Metric {code} has no name',
  'issue.METRIC_MISSING_CODE': '"{name}" has no code',
  'issue.METRIC_DUPLICATE_CODE': 'Code "{code}" is used by {count} metrics',
  'issue.METRIC_UNIT_MISSING': '"{name}" references a unit that no longer exists',
  'issue.METRIC_APPROVED_UNPLACED': 'Approved metric "{name}" is not placed in the structure',
  'issue.METRIC_UNPLACED': 'Draft "{name}" is not placed in the structure yet',
  'issue.METRIC_APPROVED_UNBOUND': 'Approved metric "{name}" has no TT or GD binding',
  'issue.PLACEMENT_ORPHAN': 'A structural placement points to a missing metric or group',
  'issue.STRUCTURE_CYCLE': 'Group "{name}" is part of a parent cycle',
  'issue.STRUCTURE_ORPHAN': 'Group "{name}" references a missing parent',
  'issue.STRUCTURE_MISSING_NAME': 'A structure group has no name',
  'issue.STRUCTURE_DUPLICATE_CODE': 'Group code "{code}" is duplicated',
  'issue.REPORT_CYCLE': 'Report item "{name}" is part of a parent cycle',
  'issue.REPORT_ORPHAN': 'Report item "{name}" references a missing parent',
  'issue.REPORT_PARENT_NOT_FOLDER': '"{name}" sits under "{parent}", which is a report, not a folder',
  'issue.REPORT_MISSING_NAME': 'A report item has no name',
  'issue.REPORT_DUPLICATE_CODE': 'Report code "{code}" is duplicated',
  'issue.REPORT_EMPTY': 'Report "{name}" shows no metric yet',
  'issue.REPORT_LINK_ORPHAN': 'A metric ↔ report link points to a missing metric or report',
  'issue.REPORT_LINK_TO_FOLDER': '"{metric}" is linked to "{report}", which is a folder',
  'issue.REPORT_LINK_DUPLICATE': '"{metric}" is linked to "{report}" more than once',
  'issue.BINDING_ORPHAN': 'A binding points to a missing metric or scenario',
  'issue.BINDING_DUPLICATE': '"{metric}" has {count} bindings for {scenario}',
  'issue.BINDING_FORMULA_EMPTY': '{scenario} formula binding of "{metric}" has no formula',
  'issue.BINDING_FORMULA_SYNTAX': '{scenario} formula of "{metric}": {detail}',
  'issue.BINDING_FORMULA_FREE_TEXT': '{scenario} formula of "{metric}" is free text with {count} declared reference(s) — not checked, not executable',
  'issue.BINDING_REF_UNKNOWN_SCENARIO': '{scenario} formula of "{metric}": {ref} uses an unknown scenario',
  'issue.BINDING_REF_AMBIGUOUS': '{scenario} formula of "{metric}": {ref} matches {count} metrics',
  'issue.BINDING_REF_MISSING': '{scenario} formula of "{metric}": {ref} does not match any metric',
  'issue.BINDING_REF_TARGET_UNBOUND': '{scenario} formula of "{metric}" uses "{target}", which has no {targetScenario} binding',
  'issue.BINDING_CROSS_SCENARIO': '{scenario} formula of "{metric}" references {ref} from {targetScenario} (explicit cross-scenario)',
  'issue.BINDING_SOURCE_MISSING_INFO': '{scenario} source binding of "{metric}" has no source information',
  'issue.BINDING_ASSUMPTION_MISSING_VALUE': '{scenario} assumption of "{metric}" has no value',
  'issue.BINDING_ASSUMPTION_MISSING_BASIS': '{scenario} assumption of "{metric}" has no basis / rationale',
  'issue.DIMENSION_MISSING_NAME': 'Dimension {code} has no name',
  'issue.DIMENSION_DUPLICATE_CODE': 'Dimension code "{code}" is duplicated',
  'issue.MEMBER_ORPHAN': 'Member "{name}" belongs to a missing dimension',
  'issue.MEMBER_INVALID_PARENT': 'Member "{name}" has an invalid parent',
  'issue.MEMBER_CYCLE': 'Member "{name}" is part of a cyclic hierarchy',
  'issue.MEMBER_DUPLICATE_CODE': 'Member code "{code}" is duplicated in its dimension',
  'issue.METRIC_DIMENSION_ORPHAN': 'A metric ↔ dimension link points to a missing record',
  'issue.METRIC_DIMENSION_DUPLICATE': '"{metric}" is linked to "{dimension}" more than once',
  'issue.METRIC_DIMENSION_MAXLEVEL': '"{metric}" × "{dimension}": max level {maxLevel} exceeds the hierarchy depth ({depth})',
  'issue.METRIC_DIMENSION_ALLOWED_MISSING': '"{metric}" × "{dimension}": {count} allowed member(s) no longer exist',
  'issue.DEPENDENCY_CYCLE': 'Circular dependency: {path}',
  'io.restorePoints': 'Restore points',
  'io.restoreHint': 'A snapshot is taken automatically before every import, reset or clear. Restore one to undo.',
  'io.restoreEmpty': 'No restore point yet.',
  'io.restoreUnavailable': 'This browser cannot store restore points. Export a JSON backup before replacing data.',
  'io.restoreUnnamed': 'Snapshot',
  'io.restoreCounts': '{metrics} metrics · {bindings} bindings',
  'io.restore': 'Restore',
  'io.restoreTitle': 'Restore this snapshot?',
  'io.restoreMessage': 'The current data will be replaced. A restore point of it is taken first, so this is reversible too.',
  'io.restored': 'Restored {n} metrics',
  'io.undo': 'Undo',
  'io.rejected': 'This file was refused',
  'io.repaired': 'Repaired while reading the file',
  'io.repairedCount': '{n} record(s) repaired or dropped, see the import preview',
  'io.willDelete': 'Records you have now that are not in this file will be deleted',
  'io.importMessageDeleting': 'The current {n} metrics and all related records will be replaced. {lost} record(s) in collections absent from the file will be deleted.',
  'conflict.reloadOnly': 'This record can only be reloaded, not overwritten.',
  'error.duplicateRelationship': 'That relationship already exists.',
  'error.partialBatch': 'The change was only partly saved. The view now shows what is actually stored; check it and try again.',
  'error.partialBatchUnsynced': 'The change was only partly saved and the current state could not be re-read. Reload before continuing.',
  'dialog.required': 'Required',
  'io.restoreFailed': 'no restore point could be written, so this cannot be undone. Export a JSON backup.',
  'io.changeSummary': 'This import adds {add}, updates {update} and deletes {remove} record(s).',
};
