export const vi = {
  // navigation
  'nav.metrics': 'Danh mục chỉ tiêu',
  'nav.bindings': 'Gắn kịch bản',
  'nav.dependencies': 'Phụ thuộc',
  'nav.dimensions': 'Chiều phân tích',
  'nav.structure': 'Cấu trúc',
  'nav.master-data': 'Dữ liệu chủ',
  'nav.backup': 'Nhập / Xuất',
  'nav.warnings': 'Cảnh báo',
  'nav.quality': 'Chất lượng',
  'nav.warningsTitle': '{errors} lỗi · {warnings} cảnh báo · {info} thông tin',
  'nav.more': 'Thêm',
  'nav.language': 'Ngôn ngữ',
  'group.catalogue': 'Danh mục',
  'group.structure': 'Cấu trúc',
  'group.logic': 'Logic',
  'group.quality': 'Chất lượng',
  'nav.density': 'Mật độ',
  'density.comfortable': 'Thoáng',
  'density.compact': 'Gọn',
  'insights.title': 'Thông tin',
  'insights.empty': 'Chọn một dòng để xem chi tiết tại đây.',
  'insights.collapse': 'Thu gọn bảng',
  'insights.expand': 'Mở bảng',
  'insights.resize': 'Kéo để đổi cỡ',
  'insights.coverage': 'Phủ kịch bản',
  'insights.lineage': 'Dòng dữ liệu',
  'insights.usedBy': 'Được dùng bởi',
  'insights.dependsOn': 'Phụ thuộc vào',
  'insights.noIssues': 'Không có vấn đề',
  'insights.noDefinition': 'Chưa có định nghĩa.',
  'insights.noDimensions': 'Chưa gắn chiều nào.',
  'insights.editMetric': 'Sửa chỉ tiêu',
  'filters.add': 'Bộ lọc',
  'filters.clear': 'Xoá bộ lọc',
  'filters.any': 'Mọi {label}',

  // common
  'common.save': 'Lưu',
  'common.cancel': 'Huỷ',
  'common.confirm': 'Xác nhận',
  'common.create': 'Tạo',
  'common.delete': 'Xoá',
  'common.remove': 'Gỡ',
  'common.rename': 'Sửa tên',
  'common.edit': 'Sửa',
  'common.move': 'Di chuyển',
  'common.close': 'Đóng',
  'common.open': 'Mở',
  'common.more': 'Thao tác khác',
  'common.noResults': 'Không có kết quả',

  // metric fields / enums
  'metric.field.name': 'Tên chỉ tiêu',
  'metric.field.code': 'Mã',
  'metric.field.aliases': 'Tên gọi khác',
  'metric.field.unit': 'Đơn vị tính',
  'metric.field.unitId': 'Đơn vị tính',
  'metric.field.definition': 'Định nghĩa',
  'metric.field.owner': 'Đơn vị phụ trách',
  'metric.field.owners': 'Đơn vị phụ trách',
  'drawer.ownersPlaceholder': 'Gõ tên, Enter để thêm',
  'drawer.ownersHint': 'Có thể nhiều đơn vị phụ trách: mỗi đơn vị một thẻ.',
  'metric.field.role': 'Vai trò',
  'metric.field.status': 'Trạng thái',
  'metric.field.tags': 'Nhãn',
  'metric.status.draft': 'Nháp',
  'metric.status.approved': 'Đã duyệt',
  'metric.status.deprecated': 'Ngừng dùng',
  'metric.role.metric': 'Metric',
  'metric.role.kpi': 'KPI',
  'metric.role.indicator': 'Indicator',
  'metric.role.index': 'Index',

  // bindings
  'binding.type': 'Loại gắn kết',
  'binding.type.source': 'Nguồn',
  'binding.type.formula': 'Công thức',
  'binding.type.assumption': 'Giả định',
  'binding.type.none': 'Chưa có',
  'binding.type.missing': 'Thiếu',
  'binding.type.source.short': 'Nguồn',
  'binding.type.formula.short': 'Công thức',
  'binding.type.assumption.short': 'Giả định',
  'binding.type.none.short': '—',
  'binding.type.missing.short': 'Thiếu',
  'binding.status': 'Trạng thái gắn kết',
  'binding.status.draft': 'Nháp',
  'binding.status.approved': 'Đã duyệt',
  'binding.noneHint': 'Chưa gắn kết cho {scenario}. Chọn Nguồn, Công thức hoặc Giả định để xác định cách chỉ tiêu này lấy giá trị trong kịch bản này.',
  'binding.source.system': 'Hệ thống nguồn',
  'binding.source.dataset': 'Bảng / bộ dữ liệu',
  'binding.source.field': 'Trường dữ liệu',
  'binding.source.frequency': 'Tần suất',
  'binding.source.owner': 'Chủ dữ liệu',
  'binding.assumption.value': 'Giá trị',
  'binding.assumption.validity': 'Hiệu lực từ → đến',
  'binding.assumption.basis': 'Căn cứ',
  'binding.assumption.basisPlaceholder': 'Con số này lấy từ đâu? (kế hoạch, chuẩn ngành, hợp đồng…)',
  'binding.formula': 'Công thức',
  'binding.formulaHint': 'Tham chiếu chỉ tiêu trong ngoặc vuông: [MÃ], [TÊN GỌI KHÁC] hoặc [Tên đầy đủ]. Chéo kịch bản: [TT:REVENUE].',
  'binding.formulaPlaceholder': 'Gõ [ để chọn chỉ tiêu, phần còn lại gõ tự do: [VOLUME] * [PRICE]',
  'binding.pickerHint': '↑ ↓ để di chuyển · Enter để chèn · Esc để đóng',
  'binding.legendResolved': 'đã khớp',
  'binding.legendMissing': 'không khớp',
  'binding.legendAmbiguous': 'nhiều kết quả',
  'binding.formulaEmpty': 'Nhập công thức để xem các tham chiếu.',
  'binding.insertReference': 'Chèn tham chiếu chỉ tiêu…',
  'binding.references': 'Tham chiếu ({n})',
  'binding.syntaxError': '{message} (vị trí {pos})',
  'binding.crossScenario': '→ {scenario}',
  'binding.targetUnbound': 'chưa gắn {scenario}',
  'binding.refMissing': 'Không có chỉ tiêu nào khớp tham chiếu này.',
  'binding.refAmbiguous': '{n} chỉ tiêu cùng khớp — chọn một:',
  'binding.refUnknownScenario': 'Kịch bản "{code}" không tồn tại.',
  'binding.useSuggestion': 'Dùng chỉ tiêu này',
  'binding.createDraft': 'Tạo chỉ tiêu nháp',
  'binding.createDraftTitle': 'Tạo chỉ tiêu nháp cho [{token}]',
  'binding.createDraftConfirm': 'Tạo nháp',
  'binding.draftCreated': 'Đã tạo nháp {code} "{name}" và liên kết',
  'binding.legacyCode': 'Mã cũ',
  'binding.legacyHint': 'Mã TT-*/GD-* từ file Excel. Chỉ là siêu dữ liệu.',
  'binding.note': 'Ghi chú',
  'binding.save': 'Lưu gắn kết {scenario}',
  'binding.saved': 'Đã lưu gắn kết {scenario}',
  'binding.savedWithMissing': 'Đã lưu. {n} tham chiếu chưa xác định được — xem cảnh báo.',
  'binding.remove': 'Gỡ gắn kết',
  'binding.removeTitle': 'Gỡ gắn kết {scenario}?',
  'binding.removeMessage': '"{metric}" sẽ không còn gắn kết {scenario}. Công thức tham chiếu tới nó trong kịch bản này sẽ hiện cảnh báo.',
  'binding.removed': 'Đã gỡ gắn kết {scenario}',
  'frequency.daily': 'Hàng ngày',
  'frequency.weekly': 'Hàng tuần',
  'frequency.monthly': 'Hàng tháng',
  'frequency.quarterly': 'Hàng quý',
  'frequency.yearly': 'Hàng năm',

  // coverage
  'coverage.all': 'Tất cả',
  'coverage.both': 'Cả hai',
  'coverage.only': 'Chỉ {scenario}',
  'coverage.none': 'Chưa gắn',
  'coverage.complete': 'Đủ',
  'coverage.partial': 'Một phần',
  'coverage.missing': 'Thiếu',

  // metric master view
  'mm.structure': 'Cấu trúc',
  'mm.contextHint': 'Nhấp một dòng để xem · nhấp đúp hoặc Enter để sửa',
  'mm.rowHint': 'Nhấp để xem · nhấp đúp để sửa · kéo vào nhóm để xếp',
  'mm.openStructure': 'Mở không gian Cấu trúc',
  'mm.openInStructure': 'Mở trong Cấu trúc',
  'mm.showMetrics': 'Xem chỉ tiêu',
  'mm.addRootNode': 'Thêm nhóm gốc',
  'mm.addSubNode': 'Thêm nhóm con',
  'mm.addSubNodeTitle': 'Thêm nhóm con dưới "{name}"',
  'mm.nodeName': 'Tên nhóm',
  'mm.nodeNamePlaceholder': 'VD: Vận hành dịch vụ',
  'mm.nodeCode': 'Mã nhóm (tuỳ chọn)',
  'mm.renameNode': 'Sửa nhóm',
  'mm.moveUp': 'Lên trên',
  'mm.moveDown': 'Xuống dưới',
  'mm.moveTo': 'Chuyển tới…',
  'mm.moveNodeTitle': 'Chuyển "{name}"',
  'mm.newParent': 'Nhóm cha mới',
  'mm.rootLevel': '(cấp gốc)',
  'mm.deleteNodeTitle': 'Xoá nhóm "{name}"?',
  'mm.deleteNodeMessage': 'Nhóm còn {metrics} chỉ tiêu và {nodes} nhóm con.',
  'mm.deleteNodeEmpty': 'Nhóm đang trống.',
  'mm.deleteMoveToParent': 'Chuyển nội dung lên nhóm cha rồi xoá',
  'mm.nodeDeleted': 'Đã xoá nhóm "{name}"',
  'mm.metricMoved': 'Đã chuyển vào "{node}"',
  'mm.allMetrics': 'Tất cả chỉ tiêu',
  'mm.unplaced': 'Chưa xếp cấu trúc',
  'mm.search': 'Tìm kiếm',
  'mm.searchPlaceholder': 'Tìm theo mã, tên, tên khác, định nghĩa…  ( / )',
  'mm.filter.anyStatus': 'Mọi trạng thái',
  'mm.filter.coverage': 'Mức gắn kết',
  'mm.filter.anyCoverage': 'Mọi mức gắn kết',
  'mm.filter.advanced': 'Lọc thêm',
  'mm.filter.anyRole': 'Mọi vai trò',
  'mm.filter.anyUnit': 'Mọi đơn vị',
  'mm.filter.dimension': 'Chiều',
  'mm.filter.anyDimension': 'Mọi chiều',
  'mm.filter.warningsOnly': 'Chỉ chỉ tiêu có cảnh báo',
  'mm.filter.reset': 'Bỏ lọc',
  'mm.newMetric': 'Chỉ tiêu mới',
  'mm.newMetricHere': 'Chỉ tiêu mới trong nhóm này',
  'mm.newMetricTitle': 'Chỉ tiêu mới',
  'mm.noPlacement': '(chưa xếp vào cấu trúc)',
  'mm.metricCreated': 'Đã tạo chỉ tiêu {code}',
  'mm.col.code': 'Mã',
  'mm.col.name': 'Tên',
  'mm.col.unit': 'ĐVT',
  'mm.col.dims': 'Chiều',
  'mm.col.dimsTitle': 'Số chiều đã liên kết',
  'mm.count': '{n} chỉ tiêu',
  'mm.countFiltered': '{n} / {total} chỉ tiêu',
  'mm.empty': 'Không có chỉ tiêu phù hợp. Đổi bộ lọc hoặc tạo mới.',

  // drawer
  'drawer.metricNotFound': 'Không tìm thấy chỉ tiêu',
  'drawer.section.definition': 'Định nghĩa',
  'drawer.section.structure': 'Cấu trúc',
  'drawer.section.dimensions': 'Chiều phân tích',
  'drawer.section.bindings': 'Gắn kịch bản',
  'drawer.section.advanced': 'Nâng cao',
  'drawer.namePlaceholder': 'Tên chỉ tiêu',
  'drawer.codeHint': 'Chỉ để nhận diện — không mã hoá cấu trúc, chiều hay kịch bản.',
  'drawer.aliasHint': 'Cách nhau bằng dấu phẩy. Tên khác cũng dùng được trong công thức.',
  'drawer.noUnit': '— không có —',
  'drawer.noPlacement': 'Chỉ tiêu này chưa được xếp vào cấu trúc.',
  'drawer.addPlacement': 'Thêm vào nhóm cấu trúc…',
  'drawer.removePlacement': 'Gỡ khỏi nhóm này',
  'drawer.primary': 'Vị trí chính',
  'drawer.makePrimary': 'Đặt làm vị trí chính',
  'drawer.noDimensions': 'Chưa liên kết chiều nào. Thêm các trục phân tích của chỉ tiêu.',
  'drawer.addDimension': 'Thêm chiều…',
  'drawer.required': 'Chiều bắt buộc',
  'drawer.requiredShort': 'bắt buộc',
  'drawer.maxLevel': 'Cấp tối đa của phân cấp',
  'drawer.maxLevelShort': 'cấp ≤',
  'drawer.memberCount': '{n} thành phần',
  'drawer.unsaved': 'Chưa lưu',
  'drawer.versionInfo': 'v{v} · {at}',
  'drawer.saveFirst': 'Lưu hoặc bỏ thay đổi trước khi mở chỉ tiêu khác.',
  'drawer.saveFirstWhat': 'Chưa lưu: {what}. Hãy lưu hoặc bỏ thay đổi trước khi mở chỉ tiêu khác.',
  'drawer.saveAllAndGo': 'Lưu tất cả rồi mở',
  'drawer.discardAndGo': 'Bỏ thay đổi rồi mở',
  'drawer.saveAllCount': 'Lưu tất cả ({n})',
  'drawer.saveCovers': 'Lưu mọi thay đổi đang chờ: {what}',
  'drawer.pending.metric': 'phần thông tin chỉ tiêu',
  'drawer.pending.binding': 'binding {scenarios}',
  'drawer.pending.bindings': 'các binding {scenarios}',
  'drawer.pending.join': ' và ',
  'drawer.saved': 'Đã lưu',
  'drawer.discardTitle': 'Bỏ thay đổi chưa lưu?',
  'drawer.discardMessage': 'Các chỉnh sửa của chỉ tiêu này chưa được lưu.',
  'drawer.discard': 'Bỏ thay đổi',
  'drawer.warningsTitle': '{n} vấn đề ở chỉ tiêu này',
  'drawer.warningsMore': '+{n} vấn đề khác trong trung tâm cảnh báo',
  'drawer.menu.openDependencies': 'Mở sơ đồ phụ thuộc',
  'drawer.menu.copyCode': 'Sao chép mã',
  'drawer.menu.delete': 'Xoá chỉ tiêu',
  'drawer.copied': 'Đã sao chép {code}',
  'drawer.deleteTitle': 'Xoá "{name}"?',
  'drawer.deleteMessage': 'Vị trí cấu trúc, gắn kết và liên kết chiều cũng bị xoá. Không thể hoàn tác.',
  'drawer.deleteMessageUsed': '{n} công thức đang tham chiếu chỉ tiêu này. Công thức giữ nguyên và sẽ báo thiếu tham chiếu.',
  'drawer.deleted': 'Đã xoá "{name}"',
  'drawer.meta.id': 'ID nội bộ',
  'drawer.meta.version': 'Phiên bản',
  'drawer.meta.created': 'Tạo lúc',
  'drawer.meta.updated': 'Cập nhật',
  'drawer.meta.legacyCodes': 'Mã cũ',
  'drawer.meta.usedBy': 'Được dùng bởi',
  'drawer.meta.usedByCount': '{n} công thức',

  // conflict
  'conflict.title': 'Đã có người khác lưu',
  'conflict.message': 'Bạn mở phiên bản {mine}; phiên bản hiện tại là {theirs}. Thay đổi của bạn chưa được lưu.',
  'conflict.deleted': 'Bản ghi này đã bị người khác xoá.',
  'conflict.staleEditor': 'Một lần lưu cho chỉ tiêu anh đã rời khỏi bị từ chối vì nó đã thay đổi ở nơi khác. Mở lại chỉ tiêu đó để xem phiên bản hiện tại.',
  'conflict.reload': 'Tải bản mới nhất',
  'conflict.overwrite': 'Ghi đè bằng bản của tôi',
  'conflict.keepEditing': 'Tiếp tục sửa',

  // bindings view
  'bindings.anyType': '{scenario}: mọi loại',
  'bindings.legacy': 'Mã cũ',
  'bindings.empty': 'Không có chỉ tiêu phù hợp bộ lọc.',
  'bindings.summary.total': 'Danh mục chỉ tiêu',
  'bindings.summary.scenario': 'Đã gắn {scenario}',
  'bindings.subtitle': 'Mỗi dòng một chỉ tiêu, mỗi ô một kịch bản.',
  'bindings.scenarioContext': 'Kịch bản',
  'bindings.allScenarios': 'Tất cả kịch bản',
  'bindings.contextHint': 'Nhấp một ô để xem · nhấp đúp hoặc Enter để sửa · ← → chuyển giữa các kịch bản',
  'bindings.pick': 'Chọn một dòng để xem chỉ tiêu, hoặc một ô để xem một liên kết.',
  'bindings.typeFilter': 'Liên kết {scenario}',
  'bindings.editBinding': 'Sửa liên kết',
  'bindings.addBinding': 'Thêm liên kết',
  'bindings.noBinding': 'Chưa có liên kết trong {scenario}.',
  'bindings.references': 'Tham chiếu',
  'bindings.noReferences': 'Không có tham chiếu.',
  'bindings.updated': 'Cập nhật',
  'bindings.legacyShort': 'Mã cũ',
  'bindings.coverageOf': 'Đã liên kết {bound}/{total} kịch bản',
  'bindings.inScenario': 'trong {scenario}',
  'bindings.openInMaster': 'Mở trong Metric Master',
  'bindings.formulaErrors': 'Lỗi công thức',

  // dependencies
  'dep.pickRoot': 'Chọn chỉ tiêu gốc…',
  'dep.subtitle': 'Một chỉ tiêu phụ thuộc vào gì và được dùng ở đâu, theo từng kịch bản.',
  'dep.root': 'Gốc',
  'dep.scenario': 'Kịch bản',
  'dep.noRoot': 'Chưa chọn gốc',
  'dep.contextHint': 'Nhấp một nút để xem · nhấp đúp để đặt làm gốc · + / − để mở rộng hoặc thu gọn',
  'dep.pickNode': 'Chọn một nút để xem liên kết và các nút lân cận.',
  'dep.inGraph': 'Trong đồ thị này',
  'dep.tableHint': 'Nhấp một cạnh để xem đích · nhấp đúp hoặc Enter để sửa',
  'dep.cross': 'Chéo',
  'dep.crossTitle': 'Theo tham chiếu qua các kịch bản',
  'dep.depthDown': 'Số cấp phụ thuộc',
  'dep.depthDownOpt': '↓ {n}',
  'dep.depthUp': 'Số cấp sử dụng',
  'dep.depthUpOpt': '↑ {n}',
  'dep.crossEdge': 'chéo kịch bản',
  'dep.legendHint': 'kéo để di chuyển · lăn chuột để phóng · nháy đúp để đặt làm gốc',
  'dep.empty': 'Chọn một chỉ tiêu gốc để xem nó phụ thuộc vào gì và được dùng ở đâu.',
  'dep.edgeCount': '{n} liên kết',
  'dep.missing': 'thiếu',
  'dep.unresolved': 'tham chiếu chưa xác định',
  'dep.missingHint': 'Không có chỉ tiêu nào khớp [{token}]. Sửa công thức hoặc tạo chỉ tiêu nháp tại:',
  'dep.fixIn': 'Sửa công thức của "{name}"',
  'dep.expandDown': 'Hiện các chỉ tiêu nó phụ thuộc',
  'dep.expandUp': 'Hiện các chỉ tiêu sử dụng nó',
  'dep.collapse': 'Thu gọn nhánh',
  'dep.dependsOn': 'Phụ thuộc vào',
  'dep.usedBy': 'Được dùng bởi',
  'dep.openMetric': 'Mở chỉ tiêu',
  'dep.makeRoot': 'Đặt làm gốc',
  'dep.stats': '{nodes} nút · {edges} liên kết hiển thị · {total} liên kết toàn danh mục · {cycles} vòng lặp',
  'dep.viewMode': 'Kiểu xem',
  'dep.mode.graph': 'Đồ thị',
  'dep.mode.table': 'Bảng',
  'dep.tableSearch': 'Tìm chỉ tiêu đích, nguồn hoặc công thức…',
  'dep.tableEmpty': 'Không có phụ thuộc nào khớp.',
  'dep.tableCount': '{n} / {total} liên kết',
  'dep.anyScenario': 'Mọi kịch bản',
  'dep.sameEdge': 'cùng kịch bản',
  'dep.col.targetScenario': 'Kịch bản',
  'dep.col.target': 'Chỉ tiêu đích',
  'dep.col.type': 'Binding',
  'dep.col.sourceScenario': 'KB nguồn',
  'dep.col.source': 'Chỉ tiêu nguồn',
  'dep.col.seq': 'TT',
  'dep.col.refType': 'Tham chiếu',
  'dep.col.dimension': 'Ngữ cảnh chiều',
  'dep.col.operator': 'Toán tử',
  'dep.unknownScenario': 'kịch bản không tồn tại',
  'dep.unknownScenarioHint': 'Không có kịch bản nào mang mã {code} nên tham chiếu này không trỏ tới đâu. Sửa tiền tố kịch bản trong công thức, hoặc thêm kịch bản tại More ▾ → Dữ liệu gốc.',
  'dep.truncated': 'Quá lớn để vẽ đầy đủ — đang hiển thị tối đa {n} nút và {e} liên kết. Giảm số cấp hoặc chọn gốc gần hơn để xem phần còn lại.',

  // dimensions
  'dims.title': 'Chiều phân tích',
  'dims.new': 'Chiều mới',
  'dims.empty': 'Chưa có chiều nào.',
  'dims.counts': '{members} thành phần · {metrics} chỉ tiêu sử dụng',
  'dims.pick': 'Chọn một chiều để quản lý thành phần.',
  'dims.members': 'Thành phần ({n}, {depth} cấp)',
  'dims.addMember': 'Thêm thành phần',
  'dims.addChild': 'Thêm thành phần con',
  'dims.addChildTitle': 'Thêm thành phần con dưới "{name}"',
  'dims.moveToRoot': 'Chuyển lên cấp gốc',
  'dims.deleteMemberTitle': 'Xoá thành phần "{name}"?',
  'dims.deleteMemberChildren': '{n} thành phần con sẽ được chuyển lên một cấp.',
  'dims.usedBy': '{n} chỉ tiêu sử dụng',
  'dims.notUsed': 'Chưa có chỉ tiêu nào dùng chiều này.',
  'dims.deleteTitle': 'Xoá chiều "{name}"?',
  'dims.deleteMessage': '{members} thành phần và {metrics} liên kết chỉ tiêu sẽ bị xoá.',
  'dims.subtitle': 'Dữ liệu chủ mà mọi chỉ tiêu có thể được cắt theo: thành phần, cấp và bí danh.',
  'dims.meta': '{dimensions} chiều · {members} thành phần',
  'dims.noMembers': 'Chưa có thành phần. Thêm một thành phần để bắt đầu phân cấp.',
  'dims.pickMember': 'Chọn một thành phần để xem chi tiết, hoặc giữ chiều đang chọn để xem tổng quan.',
  'dims.member': 'Thành phần',
  'dims.dimension': 'Chiều',
  'dims.level': 'Cấp',
  'dims.parent': 'Cha',
  'dims.rootMember': 'Thành phần gốc',
  'dims.membersStat': 'thành phần',
  'dims.depthStat': 'cấp',
  'dims.childrenStat': 'con trực tiếp',
  'dims.subtreeStat': 'trong nhánh',
  'dims.metricsStat': 'chỉ tiêu sử dụng',
  'dims.moveTo': 'Chuyển đến…',
  'dims.moveMemberTitle': 'Chuyển "{name}" vào dưới',
  'dims.newParent': 'Cha mới',
  'dims.memberMoved': 'Đã chuyển "{name}" vào "{parent}"',
  'dims.usedByList': 'Được sử dụng bởi',
  'dims.andMore': '… và {n} nữa',

  'structure.subtitle': 'Cây phân cấp quản trị: nhóm, nhóm con và vị trí của từng chỉ tiêu.',
  'structure.hierarchy': 'Phân cấp',
  'structure.empty': 'Chưa có nhóm nào. Thêm nhóm gốc để bắt đầu sắp xếp chỉ tiêu.',
  'structure.pick': 'Chọn một nhóm để xem nội dung và vị trí của nó.',
  'structure.path': 'Đường dẫn',
  'structure.contents': 'Nội dung',
  'structure.directMetrics': 'chỉ tiêu tại đây',
  'structure.totalMetrics': 'chỉ tiêu trong nhánh',
  'structure.subGroups': 'nhóm con',
  'structure.directList': 'Chỉ tiêu trong nhóm ({n})',
  'structure.andMore': '… và {n} nữa',
  'structure.meta': '{nodes} nhóm · {roots} gốc · {unplaced} chỉ tiêu chưa xếp',
  'hierarchy.expandAll': 'Mở rộng tất cả',
  'hierarchy.collapseAll': 'Thu gọn tất cả',

  // master data
  'master.units': 'Đơn vị tính',
  'master.addUnit': 'Thêm đơn vị',
  'master.usedBy': 'Số chỉ tiêu dùng',
  'master.deleteUnitTitle': 'Xoá đơn vị "{code}"?',
  'master.deleteUnitUsed': '{n} chỉ tiêu đang dùng đơn vị này và sẽ hiện cảnh báo.',
  'master.scenarios': 'Kịch bản',
  'master.scenariosHint': 'Các bối cảnh mà một chỉ tiêu có thể được gắn — ví dụ Thực tế và Kế hoạch. Định nghĩa bao nhiêu tuỳ nhu cầu; mã là thứ công thức dùng để tham chiếu chéo ([MÃ:CHỈ_TIÊU]).',
  'master.addScenario': 'Thêm kịch bản',
  'master.scenarioCode': 'Mã (ngắn, dùng trong công thức)',
  'master.scenarioName': 'Tên',
  'master.scenarioDescription': 'Mô tả',
  'master.scenarioCodeTaken': 'Mã kịch bản "{code}" đã được dùng.',
  'master.scenarioCodeInvalid': 'Mã kịch bản gồm 1–8 chữ cái hoặc chữ số, không có khoảng trắng.',
  'master.deleteScenarioTitle': 'Xoá kịch bản "{code}"?',
  'master.deleteScenarioUsed': '{n} binding thuộc kịch bản này. Hãy gỡ chúng trước; kịch bản đang dùng không thể xoá.',
  'master.deleteScenarioMessage': 'Các chỉ tiêu giữ nguyên binding ở kịch bản khác. Công thức tham chiếu [{code}:…] sẽ báo kịch bản không xác định.',
  'master.bindings': 'Gắn kết',

  // import / export
  'io.storage': 'Lưu trữ',
  'io.storagePersistent': 'Dữ liệu lưu trong trình duyệt này (IndexedDB). Hãy xuất bản sao lưu trước khi xoá dữ liệu trình duyệt.',
  'io.storageMemory': 'IndexedDB không khả dụng — dữ liệu chỉ nằm trong bộ nhớ của tab này. Hãy xuất bản sao lưu trước khi đóng.',
  'io.storageUnsaved': 'Không mở được catalogue đã lưu. Mọi thao tác trong phiên này sẽ không được lưu — hãy xuất backup trước khi đóng.',
  'io.storageSuperseded': 'Một tab khác đã mở phiên bản Metric Studio mới hơn và tiếp quản cơ sở dữ liệu. Tải lại tab này để tiếp tục.',
  'io.reload': 'Tải lại',
  'io.migrationDeduplicated': 'Đã nâng cấp lưu trữ: gỡ {n} quan hệ trùng từ phiên bản trước.',
  'io.recovery.title': 'Không mở được dữ liệu của bạn',
  'io.recovery.blocked': 'Một tab trình duyệt khác vẫn đang chạy phiên bản Metric Studio cũ và giữ cơ sở dữ liệu. Đóng tab đó rồi thử lại.',
  'io.recovery.upgradeFailed': 'Nâng cấp lưu trữ chưa hoàn tất. Thử lại một lần; nếu vẫn lỗi, tiếp tục không lưu và xuất backup từ Import / Export.',
  'io.recovery.openFailed': 'Trình duyệt từ chối mở cơ sở dữ liệu. Thử lại; nếu vẫn lỗi, tiếp tục không lưu và xuất backup.',
  'io.recovery.superseded': 'Phiên bản Metric Studio mới hơn đã tiếp quản cơ sở dữ liệu từ tab khác. Tải lại để dùng phiên bản đó.',
  'io.recovery.dataSafe': 'Không có gì bị xoá. Catalogue của bạn vẫn được lưu trong trình duyệt này.',
  'io.recovery.retry': 'Thử lại',
  'io.recovery.continue': 'Tiếp tục không lưu',
  'io.export': 'Xuất bản sao lưu',
  'io.exportHint': 'Tải toàn bộ danh mục thành một file JSON (chỉ tiêu, cấu trúc, gắn kết, chiều).',
  'io.downloadJson': 'Tải JSON',
  'io.exported': 'Đã tải bản sao lưu',
  'io.downloadBindingsCsv': 'Bảng binding (CSV)',
  'io.bindingsCsvHint': 'Mỗi dòng một chỉ tiêu × kịch bản, kèm nguyên văn công thức.',
  'io.downloadEdgesCsv': 'Bảng phụ thuộc (CSV)',
  'io.edgesCsvHint': 'Mỗi dòng một tham chiếu trong công thức: đích, nguồn, kịch bản, thứ tự, toán tử.',
  'io.import': 'Nhập bản sao lưu',
  'io.importHint': 'Thay toàn bộ dữ liệu bằng nội dung file JSON. Xem trước rồi xác nhận.',
  'io.chooseFile': 'Chọn file JSON…',
  'io.importReplace': 'Thay toàn bộ dữ liệu',
  'io.importTitle': 'Thay toàn bộ dữ liệu?',
  'io.importMessage': '{n} chỉ tiêu hiện tại và mọi bản ghi liên quan sẽ được thay bằng nội dung file.',
  'io.imported': 'Đã nhập {n} chỉ tiêu',
  'io.demo': 'Dữ liệu mẫu',
  'io.demoHint': 'Khôi phục danh mục mẫu, hoặc nạp bộ dữ liệu lớn (3.000 chỉ tiêu, 120 chiều) để kiểm tra hiệu năng.',
  'io.resetDemo': 'Khôi phục danh mục mẫu',
  'io.resetDemoTitle': 'Khôi phục dữ liệu mẫu?',
  'io.resetDemoMessage': 'Toàn bộ dữ liệu hiện tại sẽ được thay bằng danh mục mẫu.',
  'io.loadLarge': 'Nạp bộ dữ liệu lớn (3.000 chỉ tiêu)',
  'io.loadLargeTitle': 'Nạp bộ dữ liệu lớn?',
  'io.loadLargeMessage': 'Toàn bộ dữ liệu hiện tại sẽ được thay bằng danh mục sinh tự động gồm 3.000 chỉ tiêu.',
  'io.clearAll': 'Xoá toàn bộ',
  'io.clearTitle': 'Xoá toàn bộ dữ liệu?',
  'io.clearMessage': 'Mọi chỉ tiêu, gắn kết, nhóm cấu trúc và chiều sẽ bị xoá.',
  'io.replaced': 'Đã nạp {n} chỉ tiêu trong {ms} ms',
  'io.excel': 'Nhập file quy hoạch GSM',
  'io.phase2': 'Giai đoạn 2',
  'io.excelHint': 'File Excel sẽ được nhập qua quy trình đối chiếu (staging) để các dòng TT và GD mô tả cùng một chỉ tiêu được gộp có chủ đích, không bao giờ chỉ dựa vào tên.',
  'io.excelStep1': 'Bảng 1 → cấu trúc phân cấp; Giá trị chiều → chiều và thành phần.',
  'io.excelStep2': 'Bảng 2.1 / 2.2 → ứng viên gắn kết TT / GD; cột DIMxx → liên kết chỉ tiêu ↔ chiều.',
  'io.excelStep3': 'Gợi ý ghép chỉ tiêu chuẩn theo tên chuẩn hoá, đơn vị, định nghĩa, cấu trúc và bộ chiều.',
  'io.excelStep4': 'Bạn xác nhận từng cặp: gộp thành một chỉ tiêu, hoặc giữ riêng. Mã TT-*/GD-* giữ làm mã cũ của gắn kết.',
  'io.excelImport': 'Nhập file (Giai đoạn 2)',

  // warnings
  'warnings.title': 'Cảnh báo',
  'warnings.searchPlaceholder': 'Tìm vấn đề…',
  'warnings.anyEntity': 'Mọi đối tượng',
  'warnings.entity': 'Đối tượng',
  'warnings.message': 'Vấn đề',
  'warnings.rule': 'Quy tắc',
  'warnings.revalidate': 'Kiểm tra lại',
  'warnings.empty': 'Không có gì để báo.',
  'warnings.hint': 'Bấm vào một vấn đề để đi tới chỗ cần sửa.',
  'warnings.noTarget': 'Không có vị trí để mở cho vấn đề này.',
  'quality.subtitle': 'Mọi quy tắc danh mục đang vi phạm, và nơi cần đến để sửa.',
  'quality.kpi.metricsAffected': 'chỉ tiêu bị ảnh hưởng',
  'quality.kpi.clean': 'chỉ tiêu sạch',
  'quality.pick': 'Chọn một vấn đề để xem nó nói về gì và sửa ở đâu.',
  'quality.hint': 'Nhấp một vấn đề để xem · nhấp đúp hoặc Enter để đi tới nó',
  'quality.filter.severity': 'Mức độ',
  'quality.filter.entity': 'Đối tượng',
  'quality.filter.rule': 'Quy tắc',
  'quality.filter.scenario': 'Kịch bản',
  'quality.issues': '{n} vấn đề',
  'quality.issuesFiltered': '{n} / {total} vấn đề',
  'quality.about': 'Về',
  'quality.metric': 'Chỉ tiêu',
  'quality.scenario': 'Kịch bản',
  'quality.node': 'Nhóm',
  'quality.dimension': 'Chiều',
  'quality.member': 'Thành phần',
  'quality.fix': 'Đi tới vấn đề',
  'quality.openInMaster': 'Mở trong Metric Master',
  'quality.openInBindings': 'Mở trong Bindings',
  'severity.error': 'Lỗi',
  'severity.warning': 'Cảnh báo',
  'severity.info': 'Thông tin',
  'entity.metric': 'Chỉ tiêu',
  'entity.binding': 'Gắn kết',
  'entity.structure': 'Cấu trúc',
  'entity.dimension': 'Chiều',
  'entity.member': 'Thành phần',
  'entity.metricDimension': 'Chỉ tiêu × Chiều',
  'entity.metricStructure': 'Vị trí cấu trúc',

  // collections
  'collection.units': 'đơn vị',
  'collection.scenarios': 'kịch bản',
  'collection.metrics': 'chỉ tiêu',
  'collection.structureNodes': 'nhóm cấu trúc',
  'collection.metricStructures': 'vị trí',
  'collection.bindings': 'gắn kết',
  'collection.dimensions': 'chiều',
  'collection.dimensionMembers': 'thành phần chiều',
  'collection.metricDimensions': 'liên kết chỉ tiêu-chiều',

  // validation issues
  'issue.METRIC_MISSING_NAME': 'Chỉ tiêu {code} chưa có tên',
  'issue.METRIC_MISSING_CODE': '"{name}" chưa có mã',
  'issue.METRIC_DUPLICATE_CODE': 'Mã "{code}" đang dùng cho {count} chỉ tiêu',
  'issue.METRIC_UNIT_MISSING': '"{name}" tham chiếu đơn vị không còn tồn tại',
  'issue.METRIC_APPROVED_UNPLACED': 'Chỉ tiêu đã duyệt "{name}" chưa được xếp vào cấu trúc',
  'issue.METRIC_UNPLACED': 'Chỉ tiêu nháp "{name}" chưa được xếp vào cấu trúc',
  'issue.METRIC_APPROVED_UNBOUND': 'Chỉ tiêu đã duyệt "{name}" chưa gắn TT hay GD',
  'issue.PLACEMENT_ORPHAN': 'Một vị trí cấu trúc trỏ tới chỉ tiêu hoặc nhóm không tồn tại',
  'issue.STRUCTURE_CYCLE': 'Nhóm "{name}" nằm trong vòng lặp cha-con',
  'issue.STRUCTURE_ORPHAN': 'Nhóm "{name}" tham chiếu nhóm cha không tồn tại',
  'issue.STRUCTURE_MISSING_NAME': 'Một nhóm cấu trúc chưa có tên',
  'issue.STRUCTURE_DUPLICATE_CODE': 'Mã nhóm "{code}" bị trùng',
  'issue.BINDING_ORPHAN': 'Một gắn kết trỏ tới chỉ tiêu hoặc kịch bản không tồn tại',
  'issue.BINDING_DUPLICATE': '"{metric}" có {count} gắn kết cho {scenario}',
  'issue.BINDING_FORMULA_EMPTY': 'Gắn kết công thức {scenario} của "{metric}" chưa có công thức',
  'issue.BINDING_FORMULA_SYNTAX': 'Công thức {scenario} của "{metric}": {detail}',
  'issue.BINDING_REF_UNKNOWN_SCENARIO': 'Công thức {scenario} của "{metric}": {ref} dùng kịch bản không tồn tại',
  'issue.BINDING_REF_AMBIGUOUS': 'Công thức {scenario} của "{metric}": {ref} khớp {count} chỉ tiêu',
  'issue.BINDING_REF_MISSING': 'Công thức {scenario} của "{metric}": {ref} không khớp chỉ tiêu nào',
  'issue.BINDING_REF_TARGET_UNBOUND': 'Công thức {scenario} của "{metric}" dùng "{target}" nhưng chỉ tiêu này chưa gắn {targetScenario}',
  'issue.BINDING_CROSS_SCENARIO': 'Công thức {scenario} của "{metric}" tham chiếu {ref} từ {targetScenario} (chéo kịch bản có chủ đích)',
  'issue.BINDING_SOURCE_MISSING_INFO': 'Gắn kết nguồn {scenario} của "{metric}" chưa có thông tin nguồn',
  'issue.BINDING_ASSUMPTION_MISSING_VALUE': 'Giả định {scenario} của "{metric}" chưa có giá trị',
  'issue.BINDING_ASSUMPTION_MISSING_BASIS': 'Giả định {scenario} của "{metric}" chưa có căn cứ',
  'issue.DIMENSION_MISSING_NAME': 'Chiều {code} chưa có tên',
  'issue.DIMENSION_DUPLICATE_CODE': 'Mã chiều "{code}" bị trùng',
  'issue.MEMBER_ORPHAN': 'Thành phần "{name}" thuộc chiều không tồn tại',
  'issue.MEMBER_INVALID_PARENT': 'Thành phần "{name}" có cha không hợp lệ',
  'issue.MEMBER_CYCLE': 'Thành phần "{name}" nằm trong phân cấp vòng lặp',
  'issue.MEMBER_DUPLICATE_CODE': 'Mã thành phần "{code}" bị trùng trong chiều',
  'issue.METRIC_DIMENSION_ORPHAN': 'Một liên kết chỉ tiêu ↔ chiều trỏ tới bản ghi không tồn tại',
  'issue.METRIC_DIMENSION_DUPLICATE': '"{metric}" liên kết với "{dimension}" nhiều hơn một lần',
  'issue.METRIC_DIMENSION_MAXLEVEL': '"{metric}" × "{dimension}": cấp tối đa {maxLevel} vượt độ sâu phân cấp ({depth})',
  'issue.METRIC_DIMENSION_ALLOWED_MISSING': '"{metric}" × "{dimension}": {count} thành phần cho phép không còn tồn tại',
  'issue.DEPENDENCY_CYCLE': 'Phụ thuộc vòng: {path}',
  'io.restorePoints': 'Điểm khôi phục',
  'io.restoreHint': 'Hệ thống tự chụp lại dữ liệu trước mỗi lần nhập, khôi phục mẫu hoặc xoá. Khôi phục để hoàn tác.',
  'io.restoreEmpty': 'Chưa có điểm khôi phục nào.',
  'io.restoreUnavailable': 'Trình duyệt này không lưu được điểm khôi phục. Hãy xuất file JSON trước khi thay dữ liệu.',
  'io.restoreUnnamed': 'Bản chụp',
  'io.restoreCounts': '{metrics} chỉ tiêu · {bindings} gắn kết',
  'io.restore': 'Khôi phục',
  'io.restoreTitle': 'Khôi phục bản chụp này?',
  'io.restoreMessage': 'Dữ liệu hiện tại sẽ bị thay thế. Hệ thống chụp lại dữ liệu hiện tại trước, nên thao tác này cũng hoàn tác được.',
  'io.restored': 'Đã khôi phục {n} chỉ tiêu',
  'io.undo': 'Hoàn tác',
  'io.rejected': 'File bị từ chối',
  'io.repaired': 'Đã sửa khi đọc file',
  'io.repairedCount': '{n} bản ghi được sửa hoặc bỏ qua, xem phần xem trước',
  'io.willDelete': 'Những bản ghi bạn đang có mà file không chứa sẽ bị xoá',
  'io.importMessageDeleting': '{n} chỉ tiêu hiện tại và mọi bản ghi liên quan sẽ được thay thế. {lost} bản ghi thuộc các nhóm không có trong file sẽ bị xoá.',
  'conflict.reloadOnly': 'Bản ghi này chỉ có thể tải lại, không ghi đè được.',
  'error.duplicateRelationship': 'Quan hệ này đã tồn tại.',
  'io.restoreFailed': 'không tạo được điểm khôi phục nên thao tác này không hoàn tác được. Hãy xuất file JSON để sao lưu.',
  'io.changeSummary': 'Lần nhập này thêm {add}, cập nhật {update} và xoá {remove} bản ghi.',
};
